/*
Deployment script for TIGHTLYCURLY

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "TIGHTLYCURLY"
:setvar DefaultFilePrefix "TIGHTLYCURLY"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)] COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
USE [$(DatabaseName)];


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
GO

GO
PRINT N'Creating [dbo].[StateProvinces]...';


GO
CREATE TABLE [dbo].[StateProvinces] (
    [Id]              INT              IDENTITY (1, 1) NOT NULL,
    [StateProvinceId] UNIQUEIDENTIFIER NOT NULL,
    [Name]            NVARCHAR (50)    NOT NULL,
    [Abbreviation]    NVARCHAR (10)    NOT NULL,
    [CountryId]       UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]     SMALLDATETIME    NOT NULL,
    [UpdatedDate]     SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_StateProvinces] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_StateProvinces_StateProvinceId] UNIQUE NONCLUSTERED ([StateProvinceId] ASC)
);


GO
PRINT N'Creating [dbo].[Manufacturers]...';


GO
CREATE TABLE [dbo].[Manufacturers] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [ManufacturerId] UNIQUEIDENTIFIER NOT NULL,
    [Name]           NVARCHAR (1000)  NOT NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Manufacturers] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Manufacturers_ManufacturerId] UNIQUE NONCLUSTERED ([ManufacturerId] ASC)
);


GO
PRINT N'Creating [dbo].[Locales]...';


GO
CREATE TABLE [dbo].[Locales] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [LocaleId]    UNIQUEIDENTIFIER NOT NULL,
    [LCID]        INT              NOT NULL,
    [LocaleName]  NVARCHAR (40)    NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    [Code]        NVARCHAR (50)    NULL,
    CONSTRAINT [PK_Locales] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Locales_LocaleId] UNIQUE NONCLUSTERED ([LocaleId] ASC)
);


GO
PRINT N'Creating [dbo].[IngredientUris]...';


GO
CREATE TABLE [dbo].[IngredientUris] (
    [Id]              INT              IDENTITY (1, 1) NOT NULL,
    [IngredientUriId] UNIQUEIDENTIFIER NOT NULL,
    [IngredientId]    UNIQUEIDENTIFIER NOT NULL,
    [LinkKindId]      INT              NOT NULL,
    [Uri]             NVARCHAR (1000)  NOT NULL,
    [EnteredDate]     SMALLDATETIME    NOT NULL,
    [UpdatedDate]     SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_IngredientUris] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_IngredientUris_IngredientUriId] UNIQUE NONCLUSTERED ([IngredientUriId] ASC)
);


GO
PRINT N'Creating [dbo].[IngredientTitles]...';


GO
CREATE TABLE [dbo].[IngredientTitles] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [IngredientTitleId] UNIQUEIDENTIFIER NOT NULL,
    [IngredientId]      UNIQUEIDENTIFIER NOT NULL,
    [IngredientTitle]   NVARCHAR (255)   NOT NULL,
    [LocaleId]          UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_IngredientTitles] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_IngredientTitles] UNIQUE NONCLUSTERED ([IngredientTitleId] ASC)
);


GO
PRINT N'Creating [dbo].[Ingredients]...';


GO
CREATE TABLE [dbo].[Ingredients] (
    [Id]           INT              IDENTITY (1, 1) NOT NULL,
    [IngredientId] UNIQUEIDENTIFIER NOT NULL,
    [Title]        NVARCHAR (1000)  NOT NULL,
    [Description]  NVARCHAR (1000)  NOT NULL,
    [UpdatedDate]  SMALLDATETIME    NOT NULL,
    [EnteredDate]  SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Ingredients] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Ingredients_IngredientId] UNIQUE NONCLUSTERED ([IngredientId] ASC)
);


GO
PRINT N'Creating [dbo].[IngredientDescriptions]...';


GO
CREATE TABLE [dbo].[IngredientDescriptions] (
    [Id]                      INT              IDENTITY (1, 1) NOT NULL,
    [IngredientDescriptionId] UNIQUEIDENTIFIER NOT NULL,
    [IngredientId]            UNIQUEIDENTIFIER NOT NULL,
    [IngredientDescription]   NVARCHAR (255)   NOT NULL,
    [LocaleId]                INT              NOT NULL,
    [EnteredDate]             SMALLDATETIME    NOT NULL,
    [UpdatedDate]             SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_IngredientDescriptions] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_IngredientDescriptions_IngredientDescriptionId] UNIQUE NONCLUSTERED ([IngredientDescriptionId] ASC)
);


GO
PRINT N'Creating [dbo].[IngredientCategoryNames]...';


GO
CREATE TABLE [dbo].[IngredientCategoryNames] (
    [Id]                       INT              IDENTITY (1, 1) NOT NULL,
    [IngredientCategoryNameId] UNIQUEIDENTIFIER NOT NULL,
    [IngredientCategoryId]     UNIQUEIDENTIFIER NOT NULL,
    [IngredientCategoryName]   NVARCHAR (255)   NOT NULL,
    [LocaleId]                 UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]              SMALLDATETIME    NOT NULL,
    [UpdatedDate]              SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_IngredientCategoryNames] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_IngredientCategoryNames_IngredientCategoryNameId] UNIQUE NONCLUSTERED ([IngredientCategoryNameId] ASC)
);


GO
PRINT N'Creating [dbo].[IngredientCategories_CategoryTypes]...';


GO
CREATE TABLE [dbo].[IngredientCategories_CategoryTypes] (
    [Id]                                  INT              IDENTITY (1, 1) NOT NULL,
    [IngredientCategoriesCategoryTypesId] UNIQUEIDENTIFIER NOT NULL,
    [IngredientCategoryId]                UNIQUEIDENTIFIER NOT NULL,
    [CategoryTypeId]                      UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_IngredientCategories_CategoryTypes] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[IngredientCategories]...';


GO
CREATE TABLE [dbo].[IngredientCategories] (
    [Id]                   INT              IDENTITY (1, 1) NOT NULL,
    [IngredientCategoryId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]          SMALLDATETIME    NOT NULL,
    [UpdatedDate]          SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_IngredientCategories] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_IngredientCategories_IngredientCategoryId] UNIQUE NONCLUSTERED ([IngredientCategoryId] ASC)
);


GO
PRINT N'Creating [dbo].[IngredientAliases]...';


GO
CREATE TABLE [dbo].[IngredientAliases] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [IngredientAliasId] UNIQUEIDENTIFIER NOT NULL,
    [IngredientId]      UNIQUEIDENTIFIER NOT NULL,
    [IngredientAlias]   NVARCHAR (255)   NOT NULL,
    [LocaleId]          INT              NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_IngredientAliases] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_IngredientAliases_IngredientAliasId] UNIQUE NONCLUSTERED ([IngredientAliasId] ASC)
);


GO
PRINT N'Creating [dbo].[Countries]...';


GO
CREATE TABLE [dbo].[Countries] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [CountryId]   UNIQUEIDENTIFIER NOT NULL,
    [CountryName] NVARCHAR (255)   NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Countries_CountryId] UNIQUE NONCLUSTERED ([CountryId] ASC)
);


GO
PRINT N'Creating [dbo].[CategoryTypes]...';


GO
CREATE TABLE [dbo].[CategoryTypes] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [CategoryTypeId] UNIQUEIDENTIFIER NOT NULL,
    [Name]           NVARCHAR (255)   NOT NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_CategoryTypes] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_CategoryTypes_CategoryTypeId] UNIQUE NONCLUSTERED ([CategoryTypeId] ASC)
);


GO
PRINT N'Creating [dbo].[Brands]...';


GO
CREATE TABLE [dbo].[Brands] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [BrandId]        UNIQUEIDENTIFIER NOT NULL,
    [BrandName]      NVARCHAR (255)   NOT NULL,
    [ManufacturerId] UNIQUEIDENTIFIER NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Brands] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Brands_BrandId] UNIQUE NONCLUSTERED ([BrandId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductLines_Companies]...';


GO
CREATE TABLE [dbo].[ProductLines_Companies] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ProductLineId] UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]     UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductLines_Companies] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductLines]...';


GO
CREATE TABLE [dbo].[ProductLines] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ProductLineId] UNIQUEIDENTIFIER NOT NULL,
    [Name]          NVARCHAR (1000)  NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductLines] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductLines_ProductLineId] UNIQUE NONCLUSTERED ([ProductLineId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductImageUris]...';


GO
CREATE TABLE [dbo].[ProductImageUris] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ProductImageUriId] UNIQUEIDENTIFIER NOT NULL,
    [ProductId]         UNIQUEIDENTIFIER NOT NULL,
    [Uri]               NVARCHAR (1000)  NOT NULL,
    [Description]       NVARCHAR (4000)  NULL,
    [AltText]           NVARCHAR (4000)  NULL,
    [IsPrimary]         BIT              NULL,
    [Order]             INT              NULL,
    [Active]            BIT              NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductImageUris] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductImageUris_ProductImageUriId] UNIQUE NONCLUSTERED ([ProductImageUriId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductTypes]...';


GO
CREATE TABLE [dbo].[ProductTypes] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ProductTypeId] UNIQUEIDENTIFIER NOT NULL,
    [Type]          NVARCHAR (255)   NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductTypes] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductTypes_ProductTypeId] UNIQUE NONCLUSTERED ([ProductTypeId] ASC)
);


GO
PRINT N'Creating [dbo].[Products]...';


GO
CREATE TABLE [dbo].[Products] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [ProductId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Products_ProductId] UNIQUE NONCLUSTERED ([ProductId] ASC)
);


GO
PRINT N'Creating [dbo].[Companies_CompanyTypes]...';


GO
CREATE TABLE [dbo].[Companies_CompanyTypes] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [CompanyId]     UNIQUEIDENTIFIER NOT NULL,
    [CompanyTypeId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Companies_CompanyTypes] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Manufacturers_Companies]...';


GO
CREATE TABLE [dbo].[Manufacturers_Companies] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [ManufacturerId] UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]      UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Manufacturers_Companies] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[CompanyTypes]...';


GO
CREATE TABLE [dbo].[CompanyTypes] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [CompanyTypeId] UNIQUEIDENTIFIER NOT NULL,
    [Name]          NVARCHAR (1000)  NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_CompanyTypes] PRIMARY KEY CLUSTERED ([CompanyTypeId] ASC),
    CONSTRAINT [UKC_CompanyTypes_CompanyTypeId] UNIQUE NONCLUSTERED ([CompanyTypeId] ASC)
);


GO
PRINT N'Creating [dbo].[Companies]...';


GO
CREATE TABLE [dbo].[Companies] (
    [Id]              INT              IDENTITY (1, 1) NOT NULL,
    [CompanyId]       UNIQUEIDENTIFIER NOT NULL,
    [Name]            NVARCHAR (255)   NOT NULL,
    [ParentCompanyId] UNIQUEIDENTIFIER NULL,
    [EnteredDate]     SMALLDATETIME    NOT NULL,
    [UpdatedDate]     SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Companies] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Companies_CompanyId] UNIQUE NONCLUSTERED ([CompanyId] ASC)
);


GO
PRINT N'Creating [dbo].[Coordinates]...';


GO
CREATE TABLE [dbo].[Coordinates] (
    [Id]           INT              IDENTITY (1, 1) NOT NULL,
    [CoordinateId] UNIQUEIDENTIFIER NOT NULL,
    [ObjectType]   NVARCHAR (1000)  NULL,
    [ObjectId]     UNIQUEIDENTIFIER NULL,
    [Latitude]     NUMERIC (12, 12) NOT NULL,
    [Longitude]    NUMERIC (12, 12) NOT NULL,
    [EnteredDate]  SMALLDATETIME    NOT NULL,
    [UpdatedDate]  SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Coordinates] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Coordinates_CoordinateId] UNIQUE NONCLUSTERED ([CoordinateId] ASC)
);


GO
PRINT N'Creating [dbo].[Addresses]...';


GO
CREATE TABLE [dbo].[Addresses] (
    [Id]              INT              IDENTITY (1, 1) NOT NULL,
    [AddressId]       UNIQUEIDENTIFIER NOT NULL,
    [Line1]           NVARCHAR (255)   NOT NULL,
    [Line2]           NVARCHAR (255)   NULL,
    [City]            NVARCHAR (255)   NULL,
    [CountyId]        UNIQUEIDENTIFIER NULL,
    [StateProvinceId] UNIQUEIDENTIFIER NULL,
    [CountryId]       UNIQUEIDENTIFIER NULL,
    [PostalCode]      NVARCHAR (100)   NULL,
    [EnteredDate]     SMALLDATETIME    NOT NULL,
    [UpdatedDate]     SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Addresses] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Addresses_AddressId] UNIQUE NONCLUSTERED ([AddressId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductMetadata_ProductImageUris]...';


GO
CREATE TABLE [dbo].[ProductMetadata_ProductImageUris] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ProductMetadataId] UNIQUEIDENTIFIER NOT NULL,
    [ProductImageUriId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductMetadata_ProductImageUris] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductMetadata_ProductLines]...';


GO
CREATE TABLE [dbo].[ProductMetadata_ProductLines] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ProductMetadataId] UNIQUEIDENTIFIER NOT NULL,
    [ProductLineId]     UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductMetadata_ProductLines] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductMetadata_Brands]...';


GO
CREATE TABLE [dbo].[ProductMetadata_Brands] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ProductMetadataId] UNIQUEIDENTIFIER NOT NULL,
    [BrandId]           UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductMetadata_Brands] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductMetadata]...';


GO
CREATE TABLE [dbo].[ProductMetadata] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ProductMetadataId] UNIQUEIDENTIFIER NOT NULL,
    [ProductId]         UNIQUEIDENTIFIER NOT NULL,
    [Title]             NVARCHAR (1000)  NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductMetadata] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductMetadata_ProductMetadataId] UNIQUE NONCLUSTERED ([ProductMetadataId] ASC)
);


GO
PRINT N'Creating [dbo].[Copyrights]...';


GO
CREATE TABLE [dbo].[Copyrights] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [CopyrightId]    UNIQUEIDENTIFIER NOT NULL,
    [Copyright]      NVARCHAR (1000)  NOT NULL,
    [IsActive]       BIT              NULL,
    [RegisteredDate] SMALLDATETIME    NULL,
    [ExpirationDate] SMALLDATETIME    NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Copyrights] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Copyrights_CopyrightId] UNIQUE NONCLUSTERED ([CopyrightId] ASC)
);


GO
PRINT N'Creating [dbo].[Markets_Countries]...';


GO
CREATE TABLE [dbo].[Markets_Countries] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [MarketId]    UNIQUEIDENTIFIER NOT NULL,
    [CountryId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Markets_Countries] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Markets]...';


GO
CREATE TABLE [dbo].[Markets] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [MarketId]    UNIQUEIDENTIFIER NOT NULL,
    [Name]        NVARCHAR (1000)  NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Markets] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Markets_MarketId] UNIQUE NONCLUSTERED ([MarketId] ASC)
);


GO
PRINT N'Creating [dbo].[ManufacturerInfo_Companies]...';


GO
CREATE TABLE [dbo].[ManufacturerInfo_Companies] (
    [Id]                 INT              IDENTITY (1, 1) NOT NULL,
    [ManufacturerInfoId] UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]          UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]        SMALLDATETIME    NOT NULL,
    [UpdatedDate]        SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ManufacturerInfo_Companies] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ManufacturerInfo]...';


GO
CREATE TABLE [dbo].[ManufacturerInfo] (
    [Id]                 INT              IDENTITY (1, 1) NOT NULL,
    [ManufacturerInfoId] UNIQUEIDENTIFIER NOT NULL,
    [ManufacturerId]     UNIQUEIDENTIFIER NOT NULL,
    [Name]               NVARCHAR (100)   NOT NULL,
    [EnteredDate]        SMALLDATETIME    NOT NULL,
    [UpdatedDate]        SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ManufacturerInfo] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ManufacturerInfo_ManufacturerInfoId] UNIQUE NONCLUSTERED ([ManufacturerInfoId] ASC)
);


GO
PRINT N'Creating [dbo].[Locations_Coordinates]...';


GO
CREATE TABLE [dbo].[Locations_Coordinates] (
    [Id]           INT              IDENTITY (1, 1) NOT NULL,
    [LocationId]   UNIQUEIDENTIFIER NOT NULL,
    [CoordinateId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]  SMALLDATETIME    NOT NULL,
    [UpdatedDate]  SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Locations_Coordinates] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Locations]...';


GO
CREATE TABLE [dbo].[Locations] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [LocationId]  UNIQUEIDENTIFIER NOT NULL,
    [Name]        NVARCHAR (1000)  NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Locations] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Locations_LocationId] UNIQUE NONCLUSTERED ([LocationId] ASC)
);


GO
PRINT N'Creating [dbo].[Locations_Addresses]...';


GO
CREATE TABLE [dbo].[Locations_Addresses] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [LocationId]  UNIQUEIDENTIFIER NOT NULL,
    [AddressId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Locations_Addresses] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Patents_Companies]...';


GO
CREATE TABLE [dbo].[Patents_Companies] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [PatentId]    UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Patents_Companies] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[PatentAuthors_Patents]...';


GO
CREATE TABLE [dbo].[PatentAuthors_Patents] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [PatentAuthorId] UNIQUEIDENTIFIER NOT NULL,
    [PatentId]       UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_PatentAuthors_Patents] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[PatentAuthors]...';


GO
CREATE TABLE [dbo].[PatentAuthors] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [PatentAuthorId] UNIQUEIDENTIFIER NOT NULL,
    [FirstName]      NVARCHAR (50)    NULL,
    [MiddleName]     NVARCHAR (50)    NULL,
    [LastName]       NVARCHAR (50)    NULL,
    [Gender]         NVARCHAR (5)     NULL,
    [Honorific]      NVARCHAR (30)    NULL,
    [Suffix]         NVARCHAR (50)    NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_PatentAuthors] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_PatentAuthors_PatentAuthorId] UNIQUE NONCLUSTERED ([PatentAuthorId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductLines_Patents]...';


GO
CREATE TABLE [dbo].[ProductLines_Patents] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ProductLineId] UNIQUEIDENTIFIER NOT NULL,
    [PatentId]      UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductLines_Patents] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Patents]...';


GO
CREATE TABLE [dbo].[Patents] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [PatentId]       UNIQUEIDENTIFIER NOT NULL,
    [PatentNumber]   NVARCHAR (255)   NOT NULL,
    [RegisteredDate] SMALLDATETIME    NOT NULL,
    [ExpirationDate] SMALLDATETIME    NOT NULL,
    [IsActive]       BIT              NULL,
    [IsPending]      BIT              NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Patents] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Patents_PatentId] UNIQUE NONCLUSTERED ([PatentId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants]...';


GO
CREATE TABLE [dbo].[ProductVariants] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [ProductId]        UNIQUEIDENTIFIER NOT NULL,
    [Name]             NVARCHAR (100)   NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductVariants_ProductVariantId] UNIQUE NONCLUSTERED ([ProductVariantId] ASC)
);


GO
PRINT N'Creating [dbo].[Markets_Coordinates]...';


GO
CREATE TABLE [dbo].[Markets_Coordinates] (
    [Id]           INT              IDENTITY (1, 1) NOT NULL,
    [MarketId]     UNIQUEIDENTIFIER NOT NULL,
    [CoordinateId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]  SMALLDATETIME    NOT NULL,
    [UpdatedDate]  SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Markets_Coordinates] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Trademarks_Companies]...';


GO
CREATE TABLE [dbo].[Trademarks_Companies] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [TrademarkId] UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Trademarks_Companies] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Trademarks]...';


GO
CREATE TABLE [dbo].[Trademarks] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [TrademarkId]    UNIQUEIDENTIFIER NOT NULL,
    [Trademark]      NVARCHAR (100)   NOT NULL,
    [IsActive]       BIT              NULL,
    [RegisteredDate] SMALLDATETIME    NULL,
    [ExpirationDate] SMALLDATETIME    NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Trademarks] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Trademarks_TrademarkId] UNIQUE NONCLUSTERED ([TrademarkId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductLines_Copyrights]...';


GO
CREATE TABLE [dbo].[ProductLines_Copyrights] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ProductLineId] UNIQUEIDENTIFIER NOT NULL,
    [CopyrightId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductLines_Copyrights] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Copyrights_Countries]...';


GO
CREATE TABLE [dbo].[Copyrights_Countries] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [CopyrightId] UNIQUEIDENTIFIER NOT NULL,
    [CountryId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Copyrights_Countries] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Copyrights_Companies]...';


GO
CREATE TABLE [dbo].[Copyrights_Companies] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [CopyrightId] UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Copyrights_Companies] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Patents_Countries]...';


GO
CREATE TABLE [dbo].[Patents_Countries] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [PatentId]    UNIQUEIDENTIFIER NOT NULL,
    [CountryId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Patents_Countries] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_Brands]...';


GO
CREATE TABLE [dbo].[ProductVariants_Brands] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [BrandId]          UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_Brands] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_Manufacturers]...';


GO
CREATE TABLE [dbo].[ProductVariants_Manufacturers] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [ManufacturerId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_Manufacturers] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Brands_Trademarks]...';


GO
CREATE TABLE [dbo].[Brands_Trademarks] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [BrandId]     UNIQUEIDENTIFIER NOT NULL,
    [TrademarkId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Brands_Trademarks] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Brands_Copyrights]...';


GO
CREATE TABLE [dbo].[Brands_Copyrights] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [BrandId]     UNIQUEIDENTIFIER NOT NULL,
    [CopyrightId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Brands_Copyrights] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductLines_Trademarks]...';


GO
CREATE TABLE [dbo].[ProductLines_Trademarks] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ProductLineId] UNIQUEIDENTIFIER NOT NULL,
    [TrademarkId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductLines_Trademarks] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Trademarks_Countries]...';


GO
CREATE TABLE [dbo].[Trademarks_Countries] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [TrademarkId] UNIQUEIDENTIFIER NOT NULL,
    [CountryId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Trademarks_Countries] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_LocationsSoldAt]...';


GO
CREATE TABLE [dbo].[ProductVariants_LocationsSoldAt] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [LocationId]       UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_LocationsSoldAt] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductRevisionHistory]...';


GO
CREATE TABLE [dbo].[ProductRevisionHistory] (
    [Id]                       INT              IDENTITY (1, 1) NOT NULL,
    [ProductRevisionHistoryId] UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantId]         UNIQUEIDENTIFIER NOT NULL,
    [PreviousVariant]          XML              NOT NULL,
    [CurrentVariant]           XML              NOT NULL,
    [Comments]                 NVARCHAR (MAX)   NULL,
    [Notes]                    NVARCHAR (MAX)   NULL,
    [EnteredDate]              SMALLDATETIME    NOT NULL,
    [UpdatedDate]              SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductRevisionHistory] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductRevisionHistory_ProductRevisionHistoryId] UNIQUE NONCLUSTERED ([ProductRevisionHistoryId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_IngredientInfos]...';


GO
CREATE TABLE [dbo].[ProductVariants_IngredientInfos] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [IngredientInfoId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_IngredientInfos] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[IngredientInfos]...';


GO
CREATE TABLE [dbo].[IngredientInfos] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [IngredientInfoId] UNIQUEIDENTIFIER NOT NULL,
    [IngredientId]     UNIQUEIDENTIFIER NOT NULL,
    [Order]            INT              NULL,
    [IsActive]         BIT              NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_IngredientInfos] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_IngredientInfos_IngredientInfoId] UNIQUE NONCLUSTERED ([IngredientInfoId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_Markets]...';


GO
CREATE TABLE [dbo].[ProductVariants_Markets] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [MarketId]         UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_Markets] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantSkus]...';


GO
CREATE TABLE [dbo].[ProductVariantSkus] (
    [Id]                  INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantSkuId] UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantId]    UNIQUEIDENTIFIER NOT NULL,
    [Sku]                 NVARCHAR (100)   NOT NULL,
    [EnteredDate]         SMALLDATETIME    NOT NULL,
    [UpdatedDate]         SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantSkus] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductVariantSkus_ProductVariantSkuId] UNIQUE NONCLUSTERED ([ProductVariantSkuId] ASC)
);


GO
PRINT N'Creating [dbo].[Asides]...';


GO
CREATE TABLE [dbo].[Asides] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [AsideId]     UNIQUEIDENTIFIER NOT NULL,
    [Text]        NVARCHAR (300)   NOT NULL,
    [Order]       INT              NULL,
    [IsActive]    BIT              NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Asides] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Asides_AsideId] UNIQUE NONCLUSTERED ([AsideId] ASC)
);


GO
PRINT N'Creating [dbo].[Users]...';


GO
CREATE TABLE [dbo].[Users] (
    [Id]     INT              IDENTITY (1, 1) NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Users_UserId] UNIQUE NONCLUSTERED ([UserId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantEditorialReviews]...';


GO
CREATE TABLE [dbo].[ProductVariantEditorialReviews] (
    [Id]                                                  INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantEditorialReviewId]                     UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantReviewId]                              UNIQUEIDENTIFIER NOT NULL,
    [ReviewedBy]                                          UNIQUEIDENTIFIER NOT NULL,
    [Review]                                              NVARCHAR (MAX)   NOT NULL,
    [Rating]                                              DECIMAL (18)     NULL,
    [ReviewDate]                                          SMALLDATETIME    NOT NULL,
    [IsActive]                                            BIT              NULL,
    [EnteredDate} SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantEditorialReviews] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductVariantEditorialReviews_ProductVariantEditorialReviewId] UNIQUE NONCLUSTERED ([ProductVariantEditorialReviewId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantReviews]...';


GO
CREATE TABLE [dbo].[ProductVariantReviews] (
    [Id]                     INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantReviewId] UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantId]       UNIQUEIDENTIFIER NOT NULL,
    [OverallRating]          DECIMAL (18)     NOT NULL,
    [EnteredDate]            SMALLDATETIME    NOT NULL,
    [UpdatedDate]            SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantReviews] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductVariantReviews_ProductVariantReviewId] UNIQUE NONCLUSTERED ([ProductVariantReviewId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_ProductImageUris]...';


GO
CREATE TABLE [dbo].[ProductVariants_ProductImageUris] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ProductImageUriId] UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantId]  UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_ProductImageUris] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_ProductCategories]...';


GO
CREATE TABLE [dbo].[ProductVariants_ProductCategories] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId]  UNIQUEIDENTIFIER NOT NULL,
    [ProductCategoryId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_ProductCategories] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductCategories]...';


GO
CREATE TABLE [dbo].[ProductCategories] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ProductCategoryId] UNIQUEIDENTIFIER NOT NULL,
    [Name]              NVARCHAR (100)   NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductCategories] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductCategories_ProductCategoryId] UNIQUE NONCLUSTERED ([ProductCategoryId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductSafetyInfos]...';


GO
CREATE TABLE [dbo].[ProductSafetyInfos] (
    [Id]                    INT              IDENTITY (1, 1) NOT NULL,
    [ProductSafetyInfoId]   UNIQUEIDENTIFIER NOT NULL,
    [ProductSafetyInfoType] SMALLINT         NOT NULL,
    [Text]                  NVARCHAR (300)   NOT NULL,
    [EnteredDate]           SMALLDATETIME    NOT NULL,
    [UpdatedDate]           SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductSafetyInfos] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductSafetyInfos_ProductSafetyInfoId] UNIQUE NONCLUSTERED ([ProductSafetyInfoId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantUserReviews_ProductImageUris]...';


GO
CREATE TABLE [dbo].[ProductVariantUserReviews_ProductImageUris] (
    [Id]                         INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantUserReviewId] UNIQUEIDENTIFIER NOT NULL,
    [ProductImageUriId]          UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]                SMALLDATETIME    NOT NULL,
    [UpdatedDate]                SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantUserReviews_ProductImageUris] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantUserReviews_Asides]...';


GO
CREATE TABLE [dbo].[ProductVariantUserReviews_Asides] (
    [Id]                         INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantUserReviewId] UNIQUEIDENTIFIER NOT NULL,
    [AsideId]                    UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]                SMALLDATETIME    NOT NULL,
    [UpdatedDate]                SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantUserReviews_Asides] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantUserReviews]...';


GO
CREATE TABLE [dbo].[ProductVariantUserReviews] (
    [Id]                                                  INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantUserReviewId]                          UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantReviewId]                              UNIQUEIDENTIFIER NOT NULL,
    [ReviewedBy]                                          UNIQUEIDENTIFIER NOT NULL,
    [Review]                                              NVARCHAR (MAX)   NOT NULL,
    [Rating]                                              DECIMAL (18)     NULL,
    [ReviewDate]                                          SMALLDATETIME    NOT NULL,
    [IsActive]                                            BIT              NULL,
    [EnteredDate} SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantUserReviews] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductVariantUserReviews_ProductVariantUserReviewId] UNIQUE NONCLUSTERED ([ProductVariantUserReviewId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantEditorialReviews_ProductImageUris]...';


GO
CREATE TABLE [dbo].[ProductVariantEditorialReviews_ProductImageUris] (
    [Id]                              INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantEditorialReviewId] UNIQUEIDENTIFIER NOT NULL,
    [ProductImageUriId]               UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]                     SMALLDATETIME    NOT NULL,
    [UpdatedDate]                     SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantEditorialReviews_ProductImageUris] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantEditorialReviews_Asides]...';


GO
CREATE TABLE [dbo].[ProductVariantEditorialReviews_Asides] (
    [Id]                              INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantEditorialReviewId] UNIQUEIDENTIFIER NOT NULL,
    [AsideId]                         UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]                     SMALLDATETIME    NOT NULL,
    [UpdatedDate]                     SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantEditorialReviews_Asides] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantDescriptions]...';


GO
CREATE TABLE [dbo].[ProductVariantDescriptions] (
    [Id]                          INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantDescriptionId] UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantId]            UNIQUEIDENTIFIER NOT NULL,
    [EnteredBy]                   UNIQUEIDENTIFIER NOT NULL,
    [Description]                 NVARCHAR (MAX)   NOT NULL,
    [EnteredDate]                 SMALLDATETIME    NOT NULL,
    [UpdatedDate]                 SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantDescriptions] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductVariantDescriptions_ProductVariantDescriptionId] UNIQUE NONCLUSTERED ([ProductVariantDescriptionId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantNotes]...';


GO
CREATE TABLE [dbo].[ProductVariantNotes] (
    [Id]                   INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantNoteId] UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantId]     UNIQUEIDENTIFIER NOT NULL,
    [EnteredBy]            UNIQUEIDENTIFIER NOT NULL,
    [Text]                 NVARCHAR (MAX)   NULL,
    [EnteredDate]          SMALLDATETIME    NOT NULL,
    [UpdatedDate]          SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantNotes] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductVariantNotes_ProductVariantNoteId] UNIQUE NONCLUSTERED ([ProductVariantNoteId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_Patents]...';


GO
CREATE TABLE [dbo].[ProductVariants_Patents] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [PatentId]         UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_Patents] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_Copyrights]...';


GO
CREATE TABLE [dbo].[ProductVariants_Copyrights] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [CopyrightId]      UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_Copyrights] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariants_ProductTypes]...';


GO
CREATE TABLE [dbo].[ProductVariants_ProductTypes] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
    [ProductTypeId]    UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]      SMALLDATETIME    NOT NULL,
    [UpdatedDate]      SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariants_ProductTypes] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProductSafetyInfos_ProductVariants]...';


GO
CREATE TABLE [dbo].[ProductSafetyInfos_ProductVariants] (
    [Id]                  INT              IDENTITY (1, 1) NOT NULL,
    [ProductSafetyInfoId] UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantId]    UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]         SMALLDATETIME    NOT NULL,
    [UpdatedDate]         SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductSafetyInfos_ProductVariants] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ContactInfos_People]...';


GO
CREATE TABLE [dbo].[ContactInfos_People] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ContactInfoId] UNIQUEIDENTIFIER NOT NULL,
    [PersonId]      UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ContactInfos_People] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[People_SocialMediaInfos]...';


GO
CREATE TABLE [dbo].[People_SocialMediaInfos] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [PersonId]          UNIQUEIDENTIFIER NOT NULL,
    [SocialMediaInfoId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_People_SocialMediaInfos] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[SocialMediaInfos]...';


GO
CREATE TABLE [dbo].[SocialMediaInfos] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [SocialMediaInfoId] UNIQUEIDENTIFIER NOT NULL,
    [SocialMediaTypeId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_SocialMediaInfos] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_SocialMediaInfos_SocialMediaInfoId] UNIQUE NONCLUSTERED ([SocialMediaInfoId] ASC)
);


GO
PRINT N'Creating [dbo].[SocialMediaTypes]...';


GO
CREATE TABLE [dbo].[SocialMediaTypes] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [SocialMediaTypeId] UNIQUEIDENTIFIER NOT NULL,
    [Name]              NVARCHAR (255)   NOT NULL,
    [Uri]               NVARCHAR (1000)  NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_SocialMediaTypes] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_SocialMediaTypes_SocialMediaTypeId] UNIQUE NONCLUSTERED ([SocialMediaTypeId] ASC)
);


GO
PRINT N'Creating [dbo].[People]...';


GO
CREATE TABLE [dbo].[People] (
    [Id]              INT              IDENTITY (1, 1) NOT NULL,
    [PersonId]        UNIQUEIDENTIFIER NOT NULL,
    [PreferredLocale] UNIQUEIDENTIFIER NULL,
    [FirstName]       NVARCHAR (100)   NULL,
    [MiddleName]      NVARCHAR (100)   NULL,
    [LastName]        NVARCHAR (100)   NULL,
    [Gender]          NCHAR (15)       NULL,
    [Honorific]       NVARCHAR (100)   NULL,
    [Suffix]          NVARCHAR (255)   NULL,
    [EnteredDate]     SMALLDATETIME    NOT NULL,
    [UpdatedDate]     SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_People_PersonId] UNIQUE NONCLUSTERED ([PersonId] ASC)
);


GO
PRINT N'Creating [dbo].[ProductVariantMetadata]...';


GO
CREATE TABLE [dbo].[ProductVariantMetadata] (
    [Id]                       INT              IDENTITY (1, 1) NOT NULL,
    [ProductVariantMetadataId] UNIQUEIDENTIFIER NOT NULL,
    [ProductVariantId]         UNIQUEIDENTIFIER NOT NULL,
    [EnteredBy]                UNIQUEIDENTIFIER NOT NULL,
    [Key]                      NVARCHAR (30)    NOT NULL,
    [Value]                    NVARCHAR (300)   NOT NULL,
    [EnteredDate]              SMALLDATETIME    NOT NULL,
    [UpdatedDate]              SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ProductVariantMetadata] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ProductVariantMetadata_ProductVariantMetadataId] UNIQUE NONCLUSTERED ([ProductVariantMetadataId] ASC)
);


GO
PRINT N'Creating [dbo].[ContactInfos_SocialMediaInfos]...';


GO
CREATE TABLE [dbo].[ContactInfos_SocialMediaInfos] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ContactInfoId]     UNIQUEIDENTIFIER NOT NULL,
    [SocialMediaInfoId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ContactInfos_SocialMediaInfos] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[EmailAddresses]...';


GO
CREATE TABLE [dbo].[EmailAddresses] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [EmailAddressId] UNIQUEIDENTIFIER NOT NULL,
    [Address]        NVARCHAR (255)   NOT NULL,
    [Verified]       BIT              NULL,
    [IsPrimary]      BIT              NULL,
    [IsActive]       BIT              NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_EmailAddresses] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_EmailAddresses_EmailAddressId] UNIQUE NONCLUSTERED ([EmailAddressId] ASC)
);


GO
PRINT N'Creating [dbo].[ContactInfos_EmailAddresses]...';


GO
CREATE TABLE [dbo].[ContactInfos_EmailAddresses] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [ContactInfoId]  UNIQUEIDENTIFIER NOT NULL,
    [EmailAddressId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]    SMALLDATETIME    NOT NULL,
    [UpdatedDate]    SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ContactInfos_EmailAddresses] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ContactInfos_PhoneNumbers]...';


GO
CREATE TABLE [dbo].[ContactInfos_PhoneNumbers] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ContactInfoId] UNIQUEIDENTIFIER NOT NULL,
    [PhoneNumberId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ContactInfos_PhoneNumbers] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[PhoneNumbers]...';


GO
CREATE TABLE [dbo].[PhoneNumbers] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [PhoneNumberId] UNIQUEIDENTIFIER NOT NULL,
    [CountryCode]   NVARCHAR (5)     NOT NULL,
    [AreaCode]      NVARCHAR (5)     NOT NULL,
    [Prefix]        NVARCHAR (5)     NOT NULL,
    [Suffix]        NVARCHAR (5)     NOT NULL,
    [Extension]     NVARCHAR (20)    NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_PhoneNumbers] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_PhoneNumbers_PhoneNumberId] UNIQUE NONCLUSTERED ([PhoneNumberId] ASC)
);


GO
PRINT N'Creating [dbo].[ContactInfos_Addresses]...';


GO
CREATE TABLE [dbo].[ContactInfos_Addresses] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ContactInfoId] UNIQUEIDENTIFIER NOT NULL,
    [AddressId]     UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ContactInfos_Addresses] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Counties]...';


GO
CREATE TABLE [dbo].[Counties] (
    [Id]              INT              IDENTITY (1, 1) NOT NULL,
    [CountyId]        UNIQUEIDENTIFIER NOT NULL,
    [Name]            NVARCHAR (255)   NOT NULL,
    [StateProvinceId] UNIQUEIDENTIFIER NULL,
    [EnteredDate]     SMALLDATETIME    NOT NULL,
    [UpdatedDate]     SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Counties] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_Counties_CountyId] UNIQUE NONCLUSTERED ([CountyId] ASC)
);


GO
PRINT N'Creating [dbo].[CompanyPositions_People]...';


GO
CREATE TABLE [dbo].[CompanyPositions_People] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [CompanyPositionId] UNIQUEIDENTIFIER NOT NULL,
    [PersonId]          UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_CompanyPositions_People] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[CompanyPositions_Companies]...';


GO
CREATE TABLE [dbo].[CompanyPositions_Companies] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [CompanyPositionId] UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]         UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_CompanyPositions_Companies] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ContactInfos_CompanyPositions]...';


GO
CREATE TABLE [dbo].[ContactInfos_CompanyPositions] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [ContactInfoId]     UNIQUEIDENTIFIER NOT NULL,
    [CompanyPositionId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ContactInfos_CompanyPositions] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[CompanyPositions]...';


GO
CREATE TABLE [dbo].[CompanyPositions] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [CompanyPositionId] UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]         UNIQUEIDENTIFIER NULL,
    [Title]             NVARCHAR (255)   NOT NULL,
    [StartDate]         SMALLDATETIME    NULL,
    [EndDate]           SMALLDATETIME    NULL,
    [IsActive]          BIT              NULL,
    [Description]       NVARCHAR (255)   NULL,
    [Notes]             NVARCHAR (MAX)   NULL,
    [Department]        NVARCHAR (255)   NULL,
    [PositionCategory]  INT              NULL,
    [EnteredDate]       SMALLDATETIME    NOT NULL,
    [UpdatedDate]       SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_CompanyPositions] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_CompanyPositions_CompanyPositionId] UNIQUE NONCLUSTERED ([CompanyPositionId] ASC)
);


GO
PRINT N'Creating [dbo].[Companies_Countries]...';


GO
CREATE TABLE [dbo].[Companies_Countries] (
    [Id]          INT              IDENTITY (1, 1) NOT NULL,
    [CompanyId]   UNIQUEIDENTIFIER NOT NULL,
    [CountryId]   UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate] SMALLDATETIME    NOT NULL,
    [UpdatedDate] SMALLDATETIME    NOT NULL
);


GO
PRINT N'Creating [dbo].[Companies_ContactInfos]...';


GO
CREATE TABLE [dbo].[Companies_ContactInfos] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [CompanyId]     UNIQUEIDENTIFIER NOT NULL,
    [ContactInfoId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_Companies_ContactInfos] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[RelationshipTypes]...';


GO
CREATE TABLE [dbo].[RelationshipTypes] (
    [Id]                 INT              IDENTITY (1, 1) NOT NULL,
    [RelationshipTypeId] UNIQUEIDENTIFIER NOT NULL,
    [Type]               NVARCHAR (255)   NOT NULL,
    [EnteredDate]        SMALLDATETIME    NOT NULL,
    [UpdatedDate]        SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_RelationshipTypes] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_RelationshipTypes] UNIQUE NONCLUSTERED ([RelationshipTypeId] ASC)
);


GO
PRINT N'Creating [dbo].[CompanyRelationships_RelationshipTypes]...';


GO
CREATE TABLE [dbo].[CompanyRelationships_RelationshipTypes] (
    [Id]                    INT              IDENTITY (1, 1) NOT NULL,
    [CompanyRelationshipId] UNIQUEIDENTIFIER NOT NULL,
    [RelationshipTypeId]    UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]           SMALLDATETIME    NOT NULL,
    [UpdatedDate]           SMALLDATETIME    NOT NULL
);


GO
PRINT N'Creating [dbo].[CompanyRelationships]...';


GO
CREATE TABLE [dbo].[CompanyRelationships] (
    [Id]                    INT              IDENTITY (1, 1) NOT NULL,
    [CompanyRelationshipId] UNIQUEIDENTIFIER NOT NULL,
    [EnteredDate]           SMALLDATETIME    NOT NULL,
    [UpdatedDate]           SMALLDATETIME    NOT NULL,
    [StartDate]             SMALLDATETIME    NULL,
    [EndDate]               SMALLDATETIME    NULL,
    [Name]                  NVARCHAR (255)   NOT NULL,
    [Notes]                 NVARCHAR (1000)  NULL,
    [ParentId]              UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_CompanyRelationships] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_CompanyRelationshipId] UNIQUE NONCLUSTERED ([CompanyRelationshipId] ASC)
);


GO
PRINT N'Creating [dbo].[ContactInfos]...';


GO
CREATE TABLE [dbo].[ContactInfos] (
    [Id]            INT              IDENTITY (1, 1) NOT NULL,
    [ContactInfoId] UNIQUEIDENTIFIER NOT NULL,
    [Title]         NVARCHAR (255)   NOT NULL,
    [Description]   NVARCHAR (255)   NULL,
    [Notes]         NVARCHAR (MAX)   NULL,
    [IsActive]      BIT              NULL,
    [EnteredDate]   SMALLDATETIME    NOT NULL,
    [UpdatedDate]   SMALLDATETIME    NOT NULL,
    CONSTRAINT [PK_ContactInfos] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UKC_ContactInfos_ContactInfoId] UNIQUE NONCLUSTERED ([ContactInfoId] ASC)
);


GO
PRINT N'Creating [dbo].[FK_StateProvinces_Countries]...';


GO
ALTER TABLE [dbo].[StateProvinces]
    ADD CONSTRAINT [FK_StateProvinces_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId]);


GO
PRINT N'Creating [dbo].[FK_Brands_Manufacturers]...';


GO
ALTER TABLE [dbo].[Brands]
    ADD CONSTRAINT [FK_Brands_Manufacturers] FOREIGN KEY ([ManufacturerId]) REFERENCES [dbo].[Manufacturers] ([ManufacturerId]);


GO
PRINT N'Creating [dbo].[FK_ProductLines_Companies_CompanyId]...';


GO
ALTER TABLE [dbo].[ProductLines_Companies]
    ADD CONSTRAINT [FK_ProductLines_Companies_CompanyId] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_ProductLines_Companies_ProductLineId]...';


GO
ALTER TABLE [dbo].[ProductLines_Companies]
    ADD CONSTRAINT [FK_ProductLines_Companies_ProductLineId] FOREIGN KEY ([ProductLineId]) REFERENCES [dbo].[ProductLines] ([ProductLineId]);


GO
PRINT N'Creating [dbo].[FK_Manufacturers_Companies_Companies]...';


GO
ALTER TABLE [dbo].[Manufacturers_Companies]
    ADD CONSTRAINT [FK_Manufacturers_Companies_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_Manufacturers_Companies_Manufacturers]...';


GO
ALTER TABLE [dbo].[Manufacturers_Companies]
    ADD CONSTRAINT [FK_Manufacturers_Companies_Manufacturers] FOREIGN KEY ([ManufacturerId]) REFERENCES [dbo].[Manufacturers] ([ManufacturerId]);


GO
PRINT N'Creating [dbo].[FK_Companies_ParentCompany]...';


GO
ALTER TABLE [dbo].[Companies]
    ADD CONSTRAINT [FK_Companies_ParentCompany] FOREIGN KEY ([ParentCompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_Addresses_StateProvinces]...';


GO
ALTER TABLE [dbo].[Addresses]
    ADD CONSTRAINT [FK_Addresses_StateProvinces] FOREIGN KEY ([StateProvinceId]) REFERENCES [dbo].[StateProvinces] ([StateProvinceId]);


GO
PRINT N'Creating [dbo].[FK_Addresses_Countries]...';


GO
ALTER TABLE [dbo].[Addresses]
    ADD CONSTRAINT [FK_Addresses_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId]);


GO
PRINT N'Creating [dbo].[FK_Addresses_Counties]...';


GO
ALTER TABLE [dbo].[Addresses]
    ADD CONSTRAINT [FK_Addresses_Counties] FOREIGN KEY ([CountyId]) REFERENCES [dbo].[Counties] ([CountyId]);


GO
PRINT N'Creating [dbo].[FK_ProductMetadata_ProductImageUris_ProductImageUris]...';


GO
ALTER TABLE [dbo].[ProductMetadata_ProductImageUris]
    ADD CONSTRAINT [FK_ProductMetadata_ProductImageUris_ProductImageUris] FOREIGN KEY ([ProductImageUriId]) REFERENCES [dbo].[ProductImageUris] ([ProductImageUriId]);


GO
PRINT N'Creating [dbo].[FK_ProductMetadata_ProductImageUris_ProductMetadata]...';


GO
ALTER TABLE [dbo].[ProductMetadata_ProductImageUris]
    ADD CONSTRAINT [FK_ProductMetadata_ProductImageUris_ProductMetadata] FOREIGN KEY ([ProductMetadataId]) REFERENCES [dbo].[ProductMetadata] ([ProductMetadataId]);


GO
PRINT N'Creating [dbo].[FK_ProductMetadata_ProductLines_ProductLines]...';


GO
ALTER TABLE [dbo].[ProductMetadata_ProductLines]
    ADD CONSTRAINT [FK_ProductMetadata_ProductLines_ProductLines] FOREIGN KEY ([ProductLineId]) REFERENCES [dbo].[ProductLines] ([ProductLineId]);


GO
PRINT N'Creating [dbo].[FK_ProductMetadata_ProductLines_ProductMetadata]...';


GO
ALTER TABLE [dbo].[ProductMetadata_ProductLines]
    ADD CONSTRAINT [FK_ProductMetadata_ProductLines_ProductMetadata] FOREIGN KEY ([ProductMetadataId]) REFERENCES [dbo].[ProductMetadata] ([ProductMetadataId]);


GO
PRINT N'Creating [dbo].[FK_ProductMetadata_Brands_Brands]...';


GO
ALTER TABLE [dbo].[ProductMetadata_Brands]
    ADD CONSTRAINT [FK_ProductMetadata_Brands_Brands] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[Brands] ([BrandId]);


GO
PRINT N'Creating [dbo].[FK_ProductMetadata_Brands_ProductMetadata]...';


GO
ALTER TABLE [dbo].[ProductMetadata_Brands]
    ADD CONSTRAINT [FK_ProductMetadata_Brands_ProductMetadata] FOREIGN KEY ([ProductMetadataId]) REFERENCES [dbo].[ProductMetadata] ([ProductMetadataId]);


GO
PRINT N'Creating [dbo].[FK_ProductMetadata_Products]...';


GO
ALTER TABLE [dbo].[ProductMetadata]
    ADD CONSTRAINT [FK_ProductMetadata_Products] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([ProductId]);


GO
PRINT N'Creating [dbo].[FK_Markets_Countries_Markets]...';


GO
ALTER TABLE [dbo].[Markets_Countries]
    ADD CONSTRAINT [FK_Markets_Countries_Markets] FOREIGN KEY ([MarketId]) REFERENCES [dbo].[Markets] ([MarketId]);


GO
PRINT N'Creating [dbo].[FK_Markets_Countries_Countries]...';


GO
ALTER TABLE [dbo].[Markets_Countries]
    ADD CONSTRAINT [FK_Markets_Countries_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId]);


GO
PRINT N'Creating [dbo].[FK_ManufacturerInfo_Companies_Companies]...';


GO
ALTER TABLE [dbo].[ManufacturerInfo_Companies]
    ADD CONSTRAINT [FK_ManufacturerInfo_Companies_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_ManufacturerInfo_Companies_ManufacturerInfo]...';


GO
ALTER TABLE [dbo].[ManufacturerInfo_Companies]
    ADD CONSTRAINT [FK_ManufacturerInfo_Companies_ManufacturerInfo] FOREIGN KEY ([ManufacturerInfoId]) REFERENCES [dbo].[ManufacturerInfo] ([ManufacturerInfoId]);


GO
PRINT N'Creating [dbo].[FK_Locations_Coordinates_Coordinates]...';


GO
ALTER TABLE [dbo].[Locations_Coordinates]
    ADD CONSTRAINT [FK_Locations_Coordinates_Coordinates] FOREIGN KEY ([CoordinateId]) REFERENCES [dbo].[Coordinates] ([CoordinateId]);


GO
PRINT N'Creating [dbo].[FK_Locations_Coordinates_Locations]...';


GO
ALTER TABLE [dbo].[Locations_Coordinates]
    ADD CONSTRAINT [FK_Locations_Coordinates_Locations] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Locations] ([LocationId]);


GO
PRINT N'Creating [dbo].[FK_Locations_Addresses_Addresses]...';


GO
ALTER TABLE [dbo].[Locations_Addresses]
    ADD CONSTRAINT [FK_Locations_Addresses_Addresses] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Addresses] ([AddressId]);


GO
PRINT N'Creating [dbo].[FK_Locations_Addresses_Locations]...';


GO
ALTER TABLE [dbo].[Locations_Addresses]
    ADD CONSTRAINT [FK_Locations_Addresses_Locations] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Locations] ([LocationId]);


GO
PRINT N'Creating [dbo].[FK_Patents_Companies_Patents]...';


GO
ALTER TABLE [dbo].[Patents_Companies]
    ADD CONSTRAINT [FK_Patents_Companies_Patents] FOREIGN KEY ([PatentId]) REFERENCES [dbo].[Patents] ([PatentId]);


GO
PRINT N'Creating [dbo].[FK_Patents_Companies_Companies]...';


GO
ALTER TABLE [dbo].[Patents_Companies]
    ADD CONSTRAINT [FK_Patents_Companies_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_PatentAuthors_Patents_Patents]...';


GO
ALTER TABLE [dbo].[PatentAuthors_Patents]
    ADD CONSTRAINT [FK_PatentAuthors_Patents_Patents] FOREIGN KEY ([PatentId]) REFERENCES [dbo].[Patents] ([PatentId]);


GO
PRINT N'Creating [dbo].[FK_PatentAuthors_Patents_PatentAuthors]...';


GO
ALTER TABLE [dbo].[PatentAuthors_Patents]
    ADD CONSTRAINT [FK_PatentAuthors_Patents_PatentAuthors] FOREIGN KEY ([PatentAuthorId]) REFERENCES [dbo].[PatentAuthors] ([PatentAuthorId]);


GO
PRINT N'Creating [dbo].[FK_ProductLines_Patents_Patents]...';


GO
ALTER TABLE [dbo].[ProductLines_Patents]
    ADD CONSTRAINT [FK_ProductLines_Patents_Patents] FOREIGN KEY ([PatentId]) REFERENCES [dbo].[Patents] ([PatentId]);


GO
PRINT N'Creating [dbo].[FK_ProductLines_Patents_ProductLines]...';


GO
ALTER TABLE [dbo].[ProductLines_Patents]
    ADD CONSTRAINT [FK_ProductLines_Patents_ProductLines] FOREIGN KEY ([ProductLineId]) REFERENCES [dbo].[ProductLines] ([ProductLineId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Products]...';


GO
ALTER TABLE [dbo].[ProductVariants]
    ADD CONSTRAINT [FK_ProductVariants_Products] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([ProductId]);


GO
PRINT N'Creating [dbo].[FK_Markets_Coordinates_Coordinates]...';


GO
ALTER TABLE [dbo].[Markets_Coordinates]
    ADD CONSTRAINT [FK_Markets_Coordinates_Coordinates] FOREIGN KEY ([CoordinateId]) REFERENCES [dbo].[Coordinates] ([CoordinateId]);


GO
PRINT N'Creating [dbo].[FK_Markets_Coordinates_Markets]...';


GO
ALTER TABLE [dbo].[Markets_Coordinates]
    ADD CONSTRAINT [FK_Markets_Coordinates_Markets] FOREIGN KEY ([MarketId]) REFERENCES [dbo].[Markets] ([MarketId]);


GO
PRINT N'Creating [dbo].[FK_Trademarks_Companies_Companies]...';


GO
ALTER TABLE [dbo].[Trademarks_Companies]
    ADD CONSTRAINT [FK_Trademarks_Companies_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_Trademarks_Companies_Trademarks]...';


GO
ALTER TABLE [dbo].[Trademarks_Companies]
    ADD CONSTRAINT [FK_Trademarks_Companies_Trademarks] FOREIGN KEY ([TrademarkId]) REFERENCES [dbo].[Trademarks] ([TrademarkId]);


GO
PRINT N'Creating [dbo].[FK_ProductLines_Copyrights_Copyrights]...';


GO
ALTER TABLE [dbo].[ProductLines_Copyrights]
    ADD CONSTRAINT [FK_ProductLines_Copyrights_Copyrights] FOREIGN KEY ([CopyrightId]) REFERENCES [dbo].[Copyrights] ([CopyrightId]);


GO
PRINT N'Creating [dbo].[FK_ProductLines_Copyrights_ProductLines]...';


GO
ALTER TABLE [dbo].[ProductLines_Copyrights]
    ADD CONSTRAINT [FK_ProductLines_Copyrights_ProductLines] FOREIGN KEY ([ProductLineId]) REFERENCES [dbo].[ProductLines] ([ProductLineId]);


GO
PRINT N'Creating [dbo].[FK_Copyrights_Countries_Countries]...';


GO
ALTER TABLE [dbo].[Copyrights_Countries]
    ADD CONSTRAINT [FK_Copyrights_Countries_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId]);


GO
PRINT N'Creating [dbo].[FK_Copyrights_Countries_Copyrights]...';


GO
ALTER TABLE [dbo].[Copyrights_Countries]
    ADD CONSTRAINT [FK_Copyrights_Countries_Copyrights] FOREIGN KEY ([CopyrightId]) REFERENCES [dbo].[Copyrights] ([CopyrightId]);


GO
PRINT N'Creating [dbo].[FK_Copyrights_Companies_Copyrights]...';


GO
ALTER TABLE [dbo].[Copyrights_Companies]
    ADD CONSTRAINT [FK_Copyrights_Companies_Copyrights] FOREIGN KEY ([CopyrightId]) REFERENCES [dbo].[Copyrights] ([CopyrightId]);


GO
PRINT N'Creating [dbo].[FK_Copyrights_Companies_Companies]...';


GO
ALTER TABLE [dbo].[Copyrights_Companies]
    ADD CONSTRAINT [FK_Copyrights_Companies_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_Patents_Countries_Countries]...';


GO
ALTER TABLE [dbo].[Patents_Countries]
    ADD CONSTRAINT [FK_Patents_Countries_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId]);


GO
PRINT N'Creating [dbo].[FK_Patents_Countries_Patents]...';


GO
ALTER TABLE [dbo].[Patents_Countries]
    ADD CONSTRAINT [FK_Patents_Countries_Patents] FOREIGN KEY ([PatentId]) REFERENCES [dbo].[Patents] ([PatentId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Brands_Brands]...';


GO
ALTER TABLE [dbo].[ProductVariants_Brands]
    ADD CONSTRAINT [FK_ProductVariants_Brands_Brands] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[Brands] ([BrandId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Brands_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_Brands]
    ADD CONSTRAINT [FK_ProductVariants_Brands_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Manufacturers_Manufacturers]...';


GO
ALTER TABLE [dbo].[ProductVariants_Manufacturers]
    ADD CONSTRAINT [FK_ProductVariants_Manufacturers_Manufacturers] FOREIGN KEY ([ManufacturerId]) REFERENCES [dbo].[Manufacturers] ([ManufacturerId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Manufacturers_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_Manufacturers]
    ADD CONSTRAINT [FK_ProductVariants_Manufacturers_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_Brands_Trademarks_Trademarks]...';


GO
ALTER TABLE [dbo].[Brands_Trademarks]
    ADD CONSTRAINT [FK_Brands_Trademarks_Trademarks] FOREIGN KEY ([TrademarkId]) REFERENCES [dbo].[Trademarks] ([TrademarkId]);


GO
PRINT N'Creating [dbo].[FK_Brands_Trademarks_Brands]...';


GO
ALTER TABLE [dbo].[Brands_Trademarks]
    ADD CONSTRAINT [FK_Brands_Trademarks_Brands] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[Brands] ([BrandId]);


GO
PRINT N'Creating [dbo].[FK_Brands_Copyrights_Copyrights]...';


GO
ALTER TABLE [dbo].[Brands_Copyrights]
    ADD CONSTRAINT [FK_Brands_Copyrights_Copyrights] FOREIGN KEY ([CopyrightId]) REFERENCES [dbo].[Copyrights] ([CopyrightId]);


GO
PRINT N'Creating [dbo].[FK_Brands_Copyrights_Brands]...';


GO
ALTER TABLE [dbo].[Brands_Copyrights]
    ADD CONSTRAINT [FK_Brands_Copyrights_Brands] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[Brands] ([BrandId]);


GO
PRINT N'Creating [dbo].[FK_Trademarks_Countries_Countries]...';


GO
ALTER TABLE [dbo].[Trademarks_Countries]
    ADD CONSTRAINT [FK_Trademarks_Countries_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId]);


GO
PRINT N'Creating [dbo].[FK_Trademarks_Countries_Trademarks]...';


GO
ALTER TABLE [dbo].[Trademarks_Countries]
    ADD CONSTRAINT [FK_Trademarks_Countries_Trademarks] FOREIGN KEY ([TrademarkId]) REFERENCES [dbo].[Trademarks] ([TrademarkId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_LocationsSoldAt_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_LocationsSoldAt]
    ADD CONSTRAINT [FK_ProductVariants_LocationsSoldAt_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_LocationsSoldAt_Locations]...';


GO
ALTER TABLE [dbo].[ProductVariants_LocationsSoldAt]
    ADD CONSTRAINT [FK_ProductVariants_LocationsSoldAt_Locations] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Locations] ([LocationId]);


GO
PRINT N'Creating [dbo].[FK_ProductRevisionHistory_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductRevisionHistory]
    ADD CONSTRAINT [FK_ProductRevisionHistory_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_IngredientInfos_IngredientInfos]...';


GO
ALTER TABLE [dbo].[ProductVariants_IngredientInfos]
    ADD CONSTRAINT [FK_ProductVariants_IngredientInfos_IngredientInfos] FOREIGN KEY ([IngredientInfoId]) REFERENCES [dbo].[IngredientInfos] ([IngredientInfoId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_IngredientInfos_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_IngredientInfos]
    ADD CONSTRAINT [FK_ProductVariants_IngredientInfos_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_IngredientInfos_Ingredients]...';


GO
ALTER TABLE [dbo].[IngredientInfos]
    ADD CONSTRAINT [FK_IngredientInfos_Ingredients] FOREIGN KEY ([IngredientId]) REFERENCES [dbo].[Ingredients] ([IngredientId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Markets_Markets]...';


GO
ALTER TABLE [dbo].[ProductVariants_Markets]
    ADD CONSTRAINT [FK_ProductVariants_Markets_Markets] FOREIGN KEY ([MarketId]) REFERENCES [dbo].[Markets] ([MarketId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Markets_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_Markets]
    ADD CONSTRAINT [FK_ProductVariants_Markets_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantSkus_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariantSkus]
    ADD CONSTRAINT [FK_ProductVariantSkus_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantEditorialReviews_Users]...';


GO
ALTER TABLE [dbo].[ProductVariantEditorialReviews]
    ADD CONSTRAINT [FK_ProductVariantEditorialReviews_Users] FOREIGN KEY ([ReviewedBy]) REFERENCES [dbo].[Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantEditorialReviews_ProductVariantReviews]...';


GO
ALTER TABLE [dbo].[ProductVariantEditorialReviews]
    ADD CONSTRAINT [FK_ProductVariantEditorialReviews_ProductVariantReviews] FOREIGN KEY ([ProductVariantReviewId]) REFERENCES [dbo].[ProductVariantReviews] ([ProductVariantReviewId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantReviews_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariantReviews]
    ADD CONSTRAINT [FK_ProductVariantReviews_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_ProductImageUris_ProductImageUris]...';


GO
ALTER TABLE [dbo].[ProductVariants_ProductImageUris]
    ADD CONSTRAINT [FK_ProductVariants_ProductImageUris_ProductImageUris] FOREIGN KEY ([ProductImageUriId]) REFERENCES [dbo].[ProductImageUris] ([ProductImageUriId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_ProductImageUris_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_ProductImageUris]
    ADD CONSTRAINT [FK_ProductVariants_ProductImageUris_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_ProductCategories_ProductCategories]...';


GO
ALTER TABLE [dbo].[ProductVariants_ProductCategories]
    ADD CONSTRAINT [FK_ProductVariants_ProductCategories_ProductCategories] FOREIGN KEY ([ProductCategoryId]) REFERENCES [dbo].[ProductCategories] ([ProductCategoryId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_ProductCategories_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_ProductCategories]
    ADD CONSTRAINT [FK_ProductVariants_ProductCategories_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantUserReviews_ProductImageUris_ProductImageUris]...';


GO
ALTER TABLE [dbo].[ProductVariantUserReviews_ProductImageUris]
    ADD CONSTRAINT [FK_ProductVariantUserReviews_ProductImageUris_ProductImageUris] FOREIGN KEY ([ProductImageUriId]) REFERENCES [dbo].[ProductImageUris] ([ProductImageUriId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantUserReviews_ProductImageUris_ProductVariantUserReviews]...';


GO
ALTER TABLE [dbo].[ProductVariantUserReviews_ProductImageUris]
    ADD CONSTRAINT [FK_ProductVariantUserReviews_ProductImageUris_ProductVariantUserReviews] FOREIGN KEY ([ProductVariantUserReviewId]) REFERENCES [dbo].[ProductVariantUserReviews] ([ProductVariantUserReviewId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantUserReviews_Asides_Asides]...';


GO
ALTER TABLE [dbo].[ProductVariantUserReviews_Asides]
    ADD CONSTRAINT [FK_ProductVariantUserReviews_Asides_Asides] FOREIGN KEY ([AsideId]) REFERENCES [dbo].[Asides] ([AsideId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantUserReviews_Users]...';


GO
ALTER TABLE [dbo].[ProductVariantUserReviews]
    ADD CONSTRAINT [FK_ProductVariantUserReviews_Users] FOREIGN KEY ([ReviewedBy]) REFERENCES [dbo].[Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantUserReviews_Asides_ProductVariantUserReviews]...';


GO
ALTER TABLE [dbo].[ProductVariantUserReviews]
    ADD CONSTRAINT [FK_ProductVariantUserReviews_Asides_ProductVariantUserReviews] FOREIGN KEY ([ProductVariantUserReviewId]) REFERENCES [dbo].[ProductVariantUserReviews] ([ProductVariantUserReviewId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantUserReviews_ProductVariantReviews]...';


GO
ALTER TABLE [dbo].[ProductVariantUserReviews]
    ADD CONSTRAINT [FK_ProductVariantUserReviews_ProductVariantReviews] FOREIGN KEY ([ProductVariantReviewId]) REFERENCES [dbo].[ProductVariantReviews] ([ProductVariantReviewId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantEditorialReviews_ProductImageUris_ProductImageUris]...';


GO
ALTER TABLE [dbo].[ProductVariantEditorialReviews_ProductImageUris]
    ADD CONSTRAINT [FK_ProductVariantEditorialReviews_ProductImageUris_ProductImageUris] FOREIGN KEY ([ProductImageUriId]) REFERENCES [dbo].[ProductImageUris] ([ProductImageUriId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantEditorialReviews_ProductImageUris_ProductVariantEditorialReviews]...';


GO
ALTER TABLE [dbo].[ProductVariantEditorialReviews_ProductImageUris]
    ADD CONSTRAINT [FK_ProductVariantEditorialReviews_ProductImageUris_ProductVariantEditorialReviews] FOREIGN KEY ([ProductVariantEditorialReviewId]) REFERENCES [dbo].[ProductVariantEditorialReviews] ([ProductVariantEditorialReviewId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantEditorialReviews_Asides_Asides]...';


GO
ALTER TABLE [dbo].[ProductVariantEditorialReviews_Asides]
    ADD CONSTRAINT [FK_ProductVariantEditorialReviews_Asides_Asides] FOREIGN KEY ([AsideId]) REFERENCES [dbo].[Asides] ([AsideId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantEditorialReviews_Asides_ProductVariantEditorialReviews]...';


GO
ALTER TABLE [dbo].[ProductVariantEditorialReviews_Asides]
    ADD CONSTRAINT [FK_ProductVariantEditorialReviews_Asides_ProductVariantEditorialReviews] FOREIGN KEY ([ProductVariantEditorialReviewId]) REFERENCES [dbo].[ProductVariantEditorialReviews] ([ProductVariantEditorialReviewId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantDescriptions_Users]...';


GO
ALTER TABLE [dbo].[ProductVariantDescriptions]
    ADD CONSTRAINT [FK_ProductVariantDescriptions_Users] FOREIGN KEY ([EnteredBy]) REFERENCES [dbo].[Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantDescriptions_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariantDescriptions]
    ADD CONSTRAINT [FK_ProductVariantDescriptions_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantNotes_Users]...';


GO
ALTER TABLE [dbo].[ProductVariantNotes]
    ADD CONSTRAINT [FK_ProductVariantNotes_Users] FOREIGN KEY ([EnteredBy]) REFERENCES [dbo].[Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantNotes_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariantNotes]
    ADD CONSTRAINT [FK_ProductVariantNotes_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Patents_Patents]...';


GO
ALTER TABLE [dbo].[ProductVariants_Patents]
    ADD CONSTRAINT [FK_ProductVariants_Patents_Patents] FOREIGN KEY ([PatentId]) REFERENCES [dbo].[Patents] ([PatentId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Patents_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_Patents]
    ADD CONSTRAINT [FK_ProductVariants_Patents_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Copyrights_Copyrights]...';


GO
ALTER TABLE [dbo].[ProductVariants_Copyrights]
    ADD CONSTRAINT [FK_ProductVariants_Copyrights_Copyrights] FOREIGN KEY ([CopyrightId]) REFERENCES [dbo].[Copyrights] ([CopyrightId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_Copyrights_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_Copyrights]
    ADD CONSTRAINT [FK_ProductVariants_Copyrights_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_ProductTypes_ProductTypes]...';


GO
ALTER TABLE [dbo].[ProductVariants_ProductTypes]
    ADD CONSTRAINT [FK_ProductVariants_ProductTypes_ProductTypes] FOREIGN KEY ([ProductTypeId]) REFERENCES [dbo].[ProductTypes] ([ProductTypeId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariants_ProductTypes_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariants_ProductTypes]
    ADD CONSTRAINT [FK_ProductVariants_ProductTypes_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductSafetyInfos_ProductVariants_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductSafetyInfos_ProductVariants]
    ADD CONSTRAINT [FK_ProductSafetyInfos_ProductVariants_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ProductSafetyInfos_ProductVariants_ProductSafetyInfos]...';


GO
ALTER TABLE [dbo].[ProductSafetyInfos_ProductVariants]
    ADD CONSTRAINT [FK_ProductSafetyInfos_ProductVariants_ProductSafetyInfos] FOREIGN KEY ([ProductSafetyInfoId]) REFERENCES [dbo].[ProductSafetyInfos] ([ProductSafetyInfoId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_People_ContactInfos]...';


GO
ALTER TABLE [dbo].[ContactInfos_People]
    ADD CONSTRAINT [FK_ContactInfos_People_ContactInfos] FOREIGN KEY ([ContactInfoId]) REFERENCES [dbo].[ContactInfos] ([ContactInfoId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_People_People]...';


GO
ALTER TABLE [dbo].[ContactInfos_People]
    ADD CONSTRAINT [FK_ContactInfos_People_People] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[People] ([PersonId]);


GO
PRINT N'Creating [dbo].[FK_People_SocialMediaInfos_SocialMediaInfos]...';


GO
ALTER TABLE [dbo].[People_SocialMediaInfos]
    ADD CONSTRAINT [FK_People_SocialMediaInfos_SocialMediaInfos] FOREIGN KEY ([SocialMediaInfoId]) REFERENCES [dbo].[SocialMediaInfos] ([SocialMediaInfoId]);


GO
PRINT N'Creating [dbo].[FK_People_SocialMediaInfos_People]...';


GO
ALTER TABLE [dbo].[People_SocialMediaInfos]
    ADD CONSTRAINT [FK_People_SocialMediaInfos_People] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[People] ([PersonId]);


GO
PRINT N'Creating [dbo].[FK_SocialMediaInfos_SocialMediaTypes]...';


GO
ALTER TABLE [dbo].[SocialMediaInfos]
    ADD CONSTRAINT [FK_SocialMediaInfos_SocialMediaTypes] FOREIGN KEY ([SocialMediaTypeId]) REFERENCES [dbo].[SocialMediaTypes] ([SocialMediaTypeId]);


GO
PRINT N'Creating [dbo].[FK_People_Locales]...';


GO
ALTER TABLE [dbo].[People]
    ADD CONSTRAINT [FK_People_Locales] FOREIGN KEY ([PreferredLocale]) REFERENCES [dbo].[Locales] ([LocaleId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantMetadata_Users]...';


GO
ALTER TABLE [dbo].[ProductVariantMetadata]
    ADD CONSTRAINT [FK_ProductVariantMetadata_Users] FOREIGN KEY ([EnteredBy]) REFERENCES [dbo].[Users] ([UserId]);


GO
PRINT N'Creating [dbo].[FK_ProductVariantMetadata_ProductVariants]...';


GO
ALTER TABLE [dbo].[ProductVariantMetadata]
    ADD CONSTRAINT [FK_ProductVariantMetadata_ProductVariants] FOREIGN KEY ([ProductVariantId]) REFERENCES [dbo].[ProductVariants] ([ProductVariantId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_SocialMediaInfos_SocialMediaInfos]...';


GO
ALTER TABLE [dbo].[ContactInfos_SocialMediaInfos]
    ADD CONSTRAINT [FK_ContactInfos_SocialMediaInfos_SocialMediaInfos] FOREIGN KEY ([SocialMediaInfoId]) REFERENCES [dbo].[SocialMediaInfos] ([SocialMediaInfoId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_SocialMediaInfos_ContactInfos]...';


GO
ALTER TABLE [dbo].[ContactInfos_SocialMediaInfos]
    ADD CONSTRAINT [FK_ContactInfos_SocialMediaInfos_ContactInfos] FOREIGN KEY ([ContactInfoId]) REFERENCES [dbo].[ContactInfos] ([ContactInfoId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_EmailAddresses_EmailAddresses]...';


GO
ALTER TABLE [dbo].[ContactInfos_EmailAddresses]
    ADD CONSTRAINT [FK_ContactInfos_EmailAddresses_EmailAddresses] FOREIGN KEY ([EmailAddressId]) REFERENCES [dbo].[EmailAddresses] ([EmailAddressId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_EmailAddresses_ContactInfos]...';


GO
ALTER TABLE [dbo].[ContactInfos_EmailAddresses]
    ADD CONSTRAINT [FK_ContactInfos_EmailAddresses_ContactInfos] FOREIGN KEY ([ContactInfoId]) REFERENCES [dbo].[ContactInfos] ([ContactInfoId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_PhoneNumbers_PhoneNumbers]...';


GO
ALTER TABLE [dbo].[ContactInfos_PhoneNumbers]
    ADD CONSTRAINT [FK_ContactInfos_PhoneNumbers_PhoneNumbers] FOREIGN KEY ([PhoneNumberId]) REFERENCES [dbo].[PhoneNumbers] ([PhoneNumberId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_PhoneNumbers_ContactInfos]...';


GO
ALTER TABLE [dbo].[ContactInfos_PhoneNumbers]
    ADD CONSTRAINT [FK_ContactInfos_PhoneNumbers_ContactInfos] FOREIGN KEY ([ContactInfoId]) REFERENCES [dbo].[ContactInfos] ([ContactInfoId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_Addresses_Addresses]...';


GO
ALTER TABLE [dbo].[ContactInfos_Addresses]
    ADD CONSTRAINT [FK_ContactInfos_Addresses_Addresses] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Addresses] ([AddressId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_Addresses_ContactInfos]...';


GO
ALTER TABLE [dbo].[ContactInfos_Addresses]
    ADD CONSTRAINT [FK_ContactInfos_Addresses_ContactInfos] FOREIGN KEY ([ContactInfoId]) REFERENCES [dbo].[ContactInfos] ([ContactInfoId]);


GO
PRINT N'Creating [dbo].[FK_CompanyPositions_People_People]...';


GO
ALTER TABLE [dbo].[CompanyPositions_People]
    ADD CONSTRAINT [FK_CompanyPositions_People_People] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[People] ([PersonId]);


GO
PRINT N'Creating [dbo].[FK_CompanyPositions_People_CompanyPositions]...';


GO
ALTER TABLE [dbo].[CompanyPositions_People]
    ADD CONSTRAINT [FK_CompanyPositions_People_CompanyPositions] FOREIGN KEY ([CompanyPositionId]) REFERENCES [dbo].[CompanyPositions] ([CompanyPositionId]);


GO
PRINT N'Creating [dbo].[FK_CompanyPositions_Companies_Companies]...';


GO
ALTER TABLE [dbo].[CompanyPositions_Companies]
    ADD CONSTRAINT [FK_CompanyPositions_Companies_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_CompanyPositions_Companies_CompanyPositions]...';


GO
ALTER TABLE [dbo].[CompanyPositions_Companies]
    ADD CONSTRAINT [FK_CompanyPositions_Companies_CompanyPositions] FOREIGN KEY ([CompanyPositionId]) REFERENCES [dbo].[CompanyPositions] ([CompanyPositionId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_CompanyPositions_CompanyPositions]...';


GO
ALTER TABLE [dbo].[ContactInfos_CompanyPositions]
    ADD CONSTRAINT [FK_ContactInfos_CompanyPositions_CompanyPositions] FOREIGN KEY ([CompanyPositionId]) REFERENCES [dbo].[CompanyPositions] ([CompanyPositionId]);


GO
PRINT N'Creating [dbo].[FK_ContactInfos_CompanyPositions_ContactInfos]...';


GO
ALTER TABLE [dbo].[ContactInfos_CompanyPositions]
    ADD CONSTRAINT [FK_ContactInfos_CompanyPositions_ContactInfos] FOREIGN KEY ([ContactInfoId]) REFERENCES [dbo].[ContactInfos] ([ContactInfoId]);


GO
PRINT N'Creating [dbo].[FK_Companies_ContactInfos_Companies]...';


GO
ALTER TABLE [dbo].[Companies_ContactInfos]
    ADD CONSTRAINT [FK_Companies_ContactInfos_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([CompanyId]);


GO
PRINT N'Creating [dbo].[FK_Companies_ContactInfos_ContactInfos]...';


GO
ALTER TABLE [dbo].[Companies_ContactInfos]
    ADD CONSTRAINT [FK_Companies_ContactInfos_ContactInfos] FOREIGN KEY ([ContactInfoId]) REFERENCES [dbo].[ContactInfos] ([ContactInfoId]);


GO
PRINT N'Creating [dbo].[FK_CompanyRelationships_RelationshipTypes_CompanyRelationships]...';


GO
ALTER TABLE [dbo].[CompanyRelationships_RelationshipTypes]
    ADD CONSTRAINT [FK_CompanyRelationships_RelationshipTypes_CompanyRelationships] FOREIGN KEY ([CompanyRelationshipId]) REFERENCES [dbo].[CompanyRelationships] ([CompanyRelationshipId]);


GO
PRINT N'Creating [dbo].[FK_CompanyRelationships_RelationshipTypes_RelationshipTypes]...';


GO
ALTER TABLE [dbo].[CompanyRelationships_RelationshipTypes]
    ADD CONSTRAINT [FK_CompanyRelationships_RelationshipTypes_RelationshipTypes] FOREIGN KEY ([RelationshipTypeId]) REFERENCES [dbo].[RelationshipTypes] ([RelationshipTypeId]);


GO
PRINT N'Creating [dbo].[FK_CompanyRelationships_Parents]...';


GO
ALTER TABLE [dbo].[CompanyRelationships]
    ADD CONSTRAINT [FK_CompanyRelationships_Parents] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[CompanyRelationships] ([CompanyRelationshipId]);


GO
PRINT N'Creating [dbo].[CSVToTable]...';


GO

CREATE FUNCTION [dbo].[CSVToTable] ( @stringInput VARCHAR(8000) )
RETURNS @OutputTable TABLE ( [Value] VARCHAR(100) )
AS
BEGIN

    DECLARE @String    VARCHAR(100)

    WHILE LEN(@StringInput) > 0
    BEGIN
        SET @String      = LEFT(@StringInput, 
                                ISNULL(NULLIF(CHARINDEX(',', @StringInput) - 1, -1),
                                LEN(@StringInput)))
        SET @StringInput = SUBSTRING(@StringInput,
                                     ISNULL(NULLIF(CHARINDEX(',', @StringInput), 0),
                                     LEN(@StringInput)) + 1, LEN(@StringInput))

        INSERT INTO @OutputTable ( [Value] )
        VALUES ( @String )
    END
    
    RETURN
END
GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
GO

GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET MULTI_USER 
    WITH ROLLBACK IMMEDIATE;


GO
PRINT N'Update complete.';


GO
