CREATE TABLE [dbo].[IngredientUris]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[IngredientUriId] UNIQUEIDENTIFIER NOT NULL,
	[IngredientId] UNIQUEIDENTIFIER NOT NULL,
	[Uri] NVARCHAR(1000) NOT NULL,
	[Comment] NVARCHAR(1000) NULL,
	[Description] NVARCHAR(1000) NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
