CREATE TABLE [dbo].[ProductVariants_IngredientInfos]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
	[IngredientInfoId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
