CREATE TABLE [dbo].[ContentArticleNotes]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ContentArticleNoteId] UNIQUEIDENTIFIER NOT NULL,
	[ContentArticleId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL,
	[Note] NVARCHAR(1000) NOT NULL,
	[EnteredByUserId] UNIQUEIDENTIFIER NOT NULL
)
