CREATE TABLE [dbo].[Locations]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[LocationId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(1000) NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
