CREATE TABLE [dbo].[MenuTexts]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[MenuTextId] UNIQUEIDENTIFIER NOT NULL,
	[MenuId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL,
	[LocaleId] UNIQUEIDENTIFIER NOT NULL,
	[Text] NVARCHAR(255) NOT NULL
)
