CREATE TABLE [dbo].[Menus]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[MenuId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
