CREATE TABLE [dbo].[IngredientRatings]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[IngredientRatingId] UNIQUEIDENTIFIER NOT NULL,
	[IngredientId] UNIQUEIDENTIFIER NOT NULL,
	[RatingTypeId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
