CREATE TABLE [dbo].[StateProvinces]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[StateProvinceId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Abbreviation] NVARCHAR(10) NOT NULL,
	[CountryId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
