CREATE TABLE [dbo].[Companies_CompanyTypes]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[CompanyId] UNIQUEIDENTIFIER NOT NULL,
	[CompanyTypeId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
