CREATE TABLE [dbo].[ContentArticleData]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ContentArticleDataId] UNIQUEIDENTIFIER NOT NULL,
	[ContentArticleId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL,
	[Text] NVARCHAR(MAX) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	[LocaleId] UNIQUEIDENTIFIER NULL
)
