CREATE TABLE [dbo].[ProductMetadata]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[ProductMetadataId] UNIQUEIDENTIFIER NOT NULL,
	[ProductId] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(1000) NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
