CREATE TABLE [dbo].[Coordinates]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[CoordinateId] UNIQUEIDENTIFIER NOT NULL,
	[ObjectType] NVARCHAR(1000) NOT NULL,
	[ObjectId] UNIQUEIDENTIFIER NOT NULL,
	[Latitude] NUMERIC(12, 12) NOT NULL,
	[Longitude] NUMERIC(12, 12) NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
