CREATE TABLE [dbo].[ProductSafetyInfos]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[ProductSafetyInfoId] UNIQUEIDENTIFIER NOT NULL,
	[ProductSafetyInfoType] NVARCHAR(30) NULL,
	[ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
	[LocaleId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredById] UNIQUEIDENTIFIER NOT NULL,
	[Text] NVARCHAR(1000) NOT NULL,
	[Order] INT NULL,
	[Source] NVARCHAR(100) NULL,
	[Notes] NVARCHAR(1000) NULL,
	[IsActive] BIT NULL,
	[EffectiveDate] SMALLDATETIME NULL,
	[StopDate] SMALLDATETIME NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
