CREATE TABLE [dbo].[Counties]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[CountyId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[StateProvinceId] UNIQUEIDENTIFIER NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
