CREATE TABLE [dbo].[RatingTypes]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[RatingTypeId] UNIQUEIDENTIFIER NOT NULL,
	[Type] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255) NULL,
	[LocaleId] UNIQUEIDENTIFIER NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
