CREATE TABLE [dbo].[Brands_Copyrights]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[BrandId] UNIQUEIDENTIFIER NOT NULL,
	[CopyrightId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
