CREATE TABLE [dbo].[Companies_Countries]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[CompanyId] UNIQUEIDENTIFIER NOT NULL,
	[CountryId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
