CREATE TABLE [dbo].[Asides]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[AsideId] UNIQUEIDENTIFIER NOT NULL,
	[Text] NVARCHAR(300) NOT NULL,
	[Order] INT NULL,
	[IsActive] BIT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
