CREATE TABLE [dbo].[ManufacturerInfo_Companies]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ManufacturerInfoId] UNIQUEIDENTIFIER NOT NULL,
	[CompanyId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
