CREATE TABLE [dbo].[CompanyPositions]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[CompanyPositionId] UNIQUEIDENTIFIER NOT NULL,
	[CompanyId] UNIQUEIDENTIFIER NULL,
	[Title] NVARCHAR(255) NOT NULL,
	[StartDate] SMALLDATETIME NULL,
	[EndDate] SMALLDATETIME NULL,
	[IsActive] BIT NULL,
	[Description] NVARCHAR(255) NULL,
	[Notes] NVARCHAR(MAX) NULL,
	[Department] NVARCHAR(255) NULL,
	[PositionCategory] INT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
