CREATE TABLE [dbo].[MessageTemplates]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[MessageTemplateId] UNIQUEIDENTIFIER NOT NULL,
	[TemplateName] NVARCHAR(255) NOT NULL,
	[Text] NVARCHAR(MAX) NOT NULL,
	[ContentType] INT NULL,
	[LocaleId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
