CREATE TABLE [dbo].[Brands_Trademarks]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[BrandId] UNIQUEIDENTIFIER NOT NULL,
	[TrademarkId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
