CREATE TABLE [dbo].[IngredientInfos]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[IngredientInfoId] UNIQUEIDENTIFIER NOT NULL,
	[IngredientId] UNIQUEIDENTIFIER NOT NULL,
	[Order] INT NULL,
	[IsActive] BIT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
