CREATE TABLE [dbo].[Patents]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[PatentId] UNIQUEIDENTIFIER NOT NULL,
	[PatentNumber] NVARCHAR(255) NOT NULL,
	[RegisteredDate] SMALLDATETIME NOT NULL,
	[ExpirationDate] SMALLDATETIME NOT NULL,
	[IsActive] BIT NULL,
	[IsPending] BIT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
