CREATE TABLE [dbo].[Markets_Countries]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[MarketId] UNIQUEIDENTIFIER NOT NULL,
	[CountryId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
