CREATE TABLE [dbo].[ProductSafetyInfos]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[ProductSafetyInfoId] UNIQUEIDENTIFIER NOT NULL,
	[ProductSafetyInfoType] SMALLINT NOT NULL,
	[ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
	[LocaleId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredById] UNIQUEIDENTIFIER NOT NULL,
	[Text] NVARCHAR(1000) NOT NULL,
	[Order] INT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
