CREATE TABLE [dbo].[Markets]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[MarketId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(1000) NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
