CREATE TABLE [dbo].[Manufacturers_Companies]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ManufacturerId] UNIQUEIDENTIFIER NOT NULL,
	[CompanyId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
