CREATE TABLE [dbo].[Copyrights]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[CopyrightId] UNIQUEIDENTIFIER NOT NULL,
	[Copyright] NVARCHAR(1000) NOT NULL,
	[IsActive] BIT NULL,
	[RegisteredDate] SMALLDATETIME NULL,
	[ExpirationDate] SMALLDATETIME NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
