CREATE TABLE [dbo].[Trademarks]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[TrademarkId] UNIQUEIDENTIFIER NOT NULL,
	[Trademark] NVARCHAR(100) NOT NULL,
	[IsActive] BIT NULL,
	[RegisteredDate] SMALLDATETIME NULL,
	[ExpirationDate] SMALLDATETIME NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)

