CREATE TABLE [dbo].[ProductVariantReviewNotes]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ProductVariantReviewNoteId] UNIQUEIDENTIFIER NOT NULL,
	[ProductVariantReviewId] UNIQUEIDENTIFIER NOT NULL,
	[Note] NVARCHAR(1000) NOT NULL,
	[EnteredById] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
