CREATE TABLE [dbo].[ProductVariantMetadata]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[ProductVariantMetadataId] UNIQUEIDENTIFIER NOT NULL,
	[ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredBy] UNIQUEIDENTIFIER NOT NULL,
	[Key] NVARCHAR(30) NOT NULL,
	[Value] NVARCHAR(300) NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
