CREATE TABLE [dbo].[IngredientComments]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[IngredientCommentId] UNIQUEIDENTIFIER NOT NULL,
	[IngredientId] UNIQUEIDENTIFIER NOT NULL,
	[LocaleId] UNIQUEIDENTIFIER NULL,
	[ParentId] UNIQUEIDENTIFIER NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
