CREATE TABLE [dbo].[IngredientNotes]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[IngredientNoteId] UNIQUEIDENTIFIER NOT NULL,
	[IngredientId] UNIQUEIDENTIFIER NOT NULL,
	[Note] NVARCHAR(1000) NOT NULL,
	[EnteredByUserId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
