CREATE TABLE [dbo].[ProductVariantNotes]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[ProductVariantNoteId] UNIQUEIDENTIFIER NOT NULL,
	[ProductVariantId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredBy] UNIQUEIDENTIFIER NOT NULL,
	[Text] NVARCHAR(MAX),
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
