CREATE TABLE [dbo].[ProductLines_Trademarks]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ProductLineId] UNIQUEIDENTIFIER NOT NULL,
	[TrademarkId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
