CREATE TABLE [dbo].[PhoneNumbers]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[PhoneNumberId] UNIQUEIDENTIFIER NOT NULL,
	[CountryCode] NVARCHAR(5) NOT NULL,
	[AreaCode] NVARCHAR(5) NOT NULL,
	[Prefix] NVARCHAR(5) NOT NULL,
	[Suffix] NVARCHAR(5) NOT NULL,
	[Extension] NVARCHAR(20) NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
