CREATE TABLE [dbo].[ContactInfos]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[ContactInfoId] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255) NULL,
	[Notes] NVARCHAR(MAX) NULL,
	[IsActive] BIT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
