CREATE TABLE [dbo].[Addresses]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[AddressId] UNIQUEIDENTIFIER NOT NULL,
	[Line1] NVARCHAR(255) NOT NULL,
	[Line2] NVARCHAR(255) NULL,
	[City] NVARCHAR(255) NULL,
	[CountyId] UNIQUEIDENTIFIER NULL,
	[StateProvinceId] UNIQUEIDENTIFIER NULL,
	[CountryId] UNIQUEIDENTIFIER NULL,
	[PostalCode] NVARCHAR(100) NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
