CREATE TABLE [dbo].[ProductTypes]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[ProductTypeId] UNIQUEIDENTIFIER NOT NULL,
	[Type] NVARCHAR(255) NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
