CREATE TABLE [dbo].[Patents_Companies]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[PatentId] UNIQUEIDENTIFIER NOT NULL,
	[CompanyId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
