CREATE TABLE [dbo].[ContentArticles]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ContentArticleId] UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT NULL,
	[Title] NVARCHAR(255) NOT NULL,
	[ContentItemId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)