CREATE TABLE [dbo].[Menus_ContentItems]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[MenuId] UNIQUEIDENTIFIER NOT NULL,
	[ContentItemId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
