CREATE TABLE [dbo].[People]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[PersonId] UNIQUEIDENTIFIER NOT NULL,
	[PreferredLocale] UNIQUEIDENTIFIER NULL,
	[FirstName] NVARCHAR(100) NULL,
	[MiddleName] NVARCHAR(100) NULL,
	[LastName] NVARCHAR(100) NULL,
	[Gender] NCHAR(15) NULL,
	[Honorific] NVARCHAR(100) NULL,
	[Suffix] NVARCHAR(255) NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
