CREATE TABLE [dbo].[SocialMediaTypes]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[SocialMediaTypeId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[Uri] NVARCHAR(1000) NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
