CREATE TABLE [dbo].[IngredientTitles]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[IngredientTitleId]	UNIQUEIDENTIFIER NOT NULL,
	[IngredientId] UNIQUEIDENTIFIER NOT NULL,
	[IngredientTitle] NVARCHAR(255) NOT NULL,
	[LocaleId] UNIQUEIDENTIFIER NOT NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL
)
