CREATE TABLE [dbo].[Brands]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[BrandId] UNIQUEIDENTIFIER NOT NULL,
	[BrandName] NVARCHAR(255) NOT NULL,
	[ManufacturerId] UNIQUEIDENTIFIER NULL,
	[EnteredDate] SMALLDATETIME NOT NULL,
	[UpdatedDate] SMALLDATETIME NOT NULL 
)
