// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Web {
	
	
	public partial class AnswerBank {
		
		protected System.Web.UI.WebControls.Content pageContent;
		
		protected System.Web.UI.WebControls.Label AllQuestionsLabel;
		
		protected System.Web.UI.WebControls.ListBox AllQuestionsList;
		
		protected System.Web.UI.WebControls.Button ViewSelectedQuestion;
		
		protected TightlyCurly.Com.Web.UserControls.SearchControl QuestionSearchControl;
		
		protected System.Web.UI.WebControls.Panel TopicsContainer;
		
		protected System.Web.UI.WebControls.Label MasterCategoriesLabel;
		
		protected System.Web.UI.WebControls.DropDownList MasterCategoriesList;
		
		protected System.Web.UI.WebControls.Panel SubcategoriesListContainer;
		
		protected System.Web.UI.WebControls.Label SubcategoriesLabel;
		
		protected System.Web.UI.WebControls.DropDownList SubcategoriesList;
		
		protected System.Web.UI.WebControls.Button ViewQuestions;
		
		protected System.Web.UI.WebControls.GridView QuestionsList;
		
		protected System.Web.UI.WebControls.Literal NoQuestionsFoundLiteral;
		
		protected System.Web.UI.WebControls.Literal QuestionLiteral;
		
		protected System.Web.UI.WebControls.Literal QuestionText;
		
		protected System.Web.UI.WebControls.Literal AnswerLiteral;
		
		protected System.Web.UI.WebControls.Literal AnswerText;
	}
}
