// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Web {
	
	
	public partial class Contact {
		
		protected System.Web.UI.WebControls.Content pageContent;
		
		protected System.Web.UI.WebControls.Panel ContactPanel;
		
		protected System.Web.UI.WebControls.Panel MessageContainer;
		
		protected System.Web.UI.WebControls.Literal MessageContainerText;
		
		protected System.Web.UI.WebControls.Panel ContactContainer;
		
		protected System.Web.UI.WebControls.Label FirstNameLabel;
		
		protected System.Web.UI.WebControls.TextBox FirstNameText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator FirstNameValidator;
		
		protected System.Web.UI.WebControls.Label LastNameLabel;
		
		protected System.Web.UI.WebControls.TextBox LastNameText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator LastNameValidator;
		
		protected System.Web.UI.WebControls.Label EmailAddressLabel;
		
		protected System.Web.UI.WebControls.TextBox EmailAddressText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator EmailAddressValidator;
		
		protected System.Web.UI.WebControls.Label CommentsLabel;
		
		protected System.Web.UI.WebControls.TextBox CommentsText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator CommentsValidator;
		
		protected System.Web.UI.WebControls.Button AddComment;
		
		protected System.Web.UI.WebControls.CheckBox SignUpBookUpdates;
	}
}
