// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Web {
	
	
	public partial class Ingredients {
		
		protected System.Web.UI.WebControls.Content pageContent;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl blurb;
		
		protected System.Web.UI.WebControls.Panel Preamble;
		
		protected TightlyCurly.Com.Web.UserControls.IngredientsControl ingredients;
	}
}
