//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TightlyCurly.Com {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TightlyCurly.Com.Web", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Hair History.
        /// </summary>
        internal static string aboutMyHairDescription {
            get {
                return ResourceManager.GetString("aboutMyHairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About My Hair.
        /// </summary>
        internal static string aboutMyHairTitle {
            get {
                return ResourceManager.GetString("aboutMyHairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string aboutPageDescription {
            get {
                return ResourceManager.GetString("aboutPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string aboutPageTitle {
            get {
                return ResourceManager.GetString("aboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string acceptableText {
            get {
                return ResourceManager.GetString("acceptableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (aka {0}).
        /// </summary>
        internal static string alsoKnownAs {
            get {
                return ResourceManager.GetString("alsoKnownAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Bank.
        /// </summary>
        internal static string answerBankDescription {
            get {
                return ResourceManager.GetString("answerBankDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Bank.
        /// </summary>
        internal static string answerBankTitle {
            get {
                return ResourceManager.GetString("answerBankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer:.
        /// </summary>
        internal static string answerText {
            get {
                return ResourceManager.GetString("answerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Subscriptions.
        /// </summary>
        internal static string availableSubscriptions {
            get {
                return ResourceManager.GetString("availableSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid.
        /// </summary>
        internal static string avoidText {
            get {
                return ResourceManager.GetString("avoidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before and After.
        /// </summary>
        internal static string beforeAndAfterDescription {
            get {
                return ResourceManager.GetString("beforeAndAfterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befores and Afters.
        /// </summary>
        internal static string beforeAndAfterTitle {
            get {
                return ResourceManager.GetString("beforeAndAfterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes of a Former Mushroom Haired Child.
        /// </summary>
        internal static string blogDescription {
            get {
                return ResourceManager.GetString("blogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string blogTitle {
            get {
                return ResourceManager.GetString("blogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        internal static string cautionText {
            get {
                return ResourceManager.GetString("cautionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a letter to search for ingredients:.
        /// </summary>
        internal static string chooseCategoryText {
            get {
                return ResourceManager.GetString("chooseCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Combing Conditioners.
        /// </summary>
        internal static string combingConditionersDescription {
            get {
                return ResourceManager.GetString("combingConditionersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combing Conditioners.
        /// </summary>
        internal static string combingConditionersTitle {
            get {
                return ResourceManager.GetString("combingConditionersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions/Comments:.
        /// </summary>
        internal static string commentsText {
            get {
                return ResourceManager.GetString("commentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your questions/comments here.
        /// </summary>
        internal static string commentsToolTip {
            get {
                return ResourceManager.GetString("commentsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a question and/or comment.
        /// </summary>
        internal static string commentsValidationMessage {
            get {
                return ResourceManager.GetString("commentsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string communityDescription {
            get {
                return ResourceManager.GetString("communityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string communityTitle {
            get {
                return ResourceManager.GetString("communityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me.
        /// </summary>
        internal static string contactMeDescription {
            get {
                return ResourceManager.GetString("contactMeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me.
        /// </summary>
        internal static string contactMeTitle {
            get {
                return ResourceManager.GetString("contactMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Curly Hair Primer.
        /// </summary>
        internal static string curlyPrimerDescription {
            get {
                return ResourceManager.GetString("curlyPrimerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curly Primer.
        /// </summary>
        internal static string curlyPrimerTitle {
            get {
                return ResourceManager.GetString("curlyPrimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Me.
        /// </summary>
        internal static string emailMeText {
            get {
                return ResourceManager.GetString("emailMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        internal static string emailText {
            get {
                return ResourceManager.GetString("emailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        internal static string emailToolTip {
            get {
                return ResourceManager.GetString("emailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        internal static string emailValidationMessage {
            get {
                return ResourceManager.GetString("emailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source(s): .
        /// </summary>
        internal static string externalLinksText {
            get {
                return ResourceManager.GetString("externalLinksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        internal static string faqsDescription {
            get {
                return ResourceManager.GetString("faqsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        internal static string faqsTitle {
            get {
                return ResourceManager.GetString("faqsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string firstNameText {
            get {
                return ResourceManager.GetString("firstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name.
        /// </summary>
        internal static string firstNameToolTip {
            get {
                return ResourceManager.GetString("firstNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        internal static string firstNameValidationMessage {
            get {
                return ResourceManager.GetString("firstNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;pageTitleDropLetter&quot;&gt;{0}&lt;/div&gt;.
        /// </summary>
        internal static string formattedSpan {
            get {
                return ResourceManager.GetString("formattedSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string goodText {
            get {
                return ResourceManager.GetString("goodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growing It Out.
        /// </summary>
        internal static string growItOutDescription {
            get {
                return ResourceManager.GetString("growItOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growing It Out.
        /// </summary>
        internal static string growItOutTitle {
            get {
                return ResourceManager.GetString("growItOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Shots.
        /// </summary>
        internal static string hairShotsDescription {
            get {
                return ResourceManager.GetString("hairShotsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Shots.
        /// </summary>
        internal static string hairShotsTitle {
            get {
                return ResourceManager.GetString("hairShotsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients Dictionary for Hair Care Products.
        /// </summary>
        internal static string ingredientsDescription {
            get {
                return ResourceManager.GetString("ingredientsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients Starting With {0}.
        /// </summary>
        internal static string ingredientsStartingWith {
            get {
                return ResourceManager.GetString("ingredientsStartingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients Dictionary .
        /// </summary>
        internal static string ingredientsTitle {
            get {
                return ResourceManager.GetString("ingredientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string lastNameText {
            get {
                return ResourceManager.GetString("lastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name.
        /// </summary>
        internal static string lastNameToolTip {
            get {
                return ResourceManager.GetString("lastNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        internal static string lastNameValidationMessage {
            get {
                return ResourceManager.GetString("lastNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Subscriptions.
        /// </summary>
        internal static string manageSubscriptionsTitle {
            get {
                return ResourceManager.GetString("manageSubscriptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string nameText {
            get {
                return ResourceManager.GetString("nameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        internal static string nameToolTip {
            get {
                return ResourceManager.GetString("nameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name is required.
        /// </summary>
        internal static string nameValidationMessage {
            get {
                return ResourceManager.GetString("nameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No question(s) found for this topic..
        /// </summary>
        internal static string noQuestionsFoundForTopicText {
            get {
                return ResourceManager.GetString("noQuestionsFoundForTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a search term..
        /// </summary>
        internal static string noSearchTermErrorMessage {
            get {
                return ResourceManager.GetString("noSearchTermErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes On Our Hair.
        /// </summary>
        internal static string notesDescription {
            get {
                return ResourceManager.GetString("notesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notesTitle {
            get {
                return ResourceManager.GetString("notesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo History of My Hair.
        /// </summary>
        internal static string photoHistoryDescription {
            get {
                return ResourceManager.GetString("photoHistoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo History.
        /// </summary>
        internal static string photoHistoryTitle {
            get {
                return ResourceManager.GetString("photoHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products I Recommend.
        /// </summary>
        internal static string productsDescription {
            get {
                return ResourceManager.GetString("productsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Products.
        /// </summary>
        internal static string productsTitle {
            get {
                return ResourceManager.GetString("productsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        internal static string questionText {
            get {
                return ResourceManager.GetString("questionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Hair Tools.
        /// </summary>
        internal static string recommendedHairToolsDescription {
            get {
                return ResourceManager.GetString("recommendedHairToolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Tools.
        /// </summary>
        internal static string recommendedHairToolsTitle {
            get {
                return ResourceManager.GetString("recommendedHairToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Reading.
        /// </summary>
        internal static string recommendedReadingDescription {
            get {
                return ResourceManager.GetString("recommendedReadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Reading.
        /// </summary>
        internal static string recommendedReadingTitle {
            get {
                return ResourceManager.GetString("recommendedReadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also:.
        /// </summary>
        internal static string relatedLinksText {
            get {
                return ResourceManager.GetString("relatedLinksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Rinsing Conditioners.
        /// </summary>
        internal static string rinsingConditionersDescription {
            get {
                return ResourceManager.GetString("rinsingConditionersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rinsing Conditioners.
        /// </summary>
        internal static string rinsingConditionersTitle {
            get {
                return ResourceManager.GetString("rinsingConditionersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a subtopic.
        /// </summary>
        internal static string selectSubTopicText {
            get {
                return ResourceManager.GetString("selectSubTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a topic.
        /// </summary>
        internal static string selectTopicText {
            get {
                return ResourceManager.GetString("selectTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Shampoos.
        /// </summary>
        internal static string shampoosDescription {
            get {
                return ResourceManager.GetString("shampoosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shampoos.
        /// </summary>
        internal static string shampoosTitle {
            get {
                return ResourceManager.GetString("shampoosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop With Teri.
        /// </summary>
        internal static string shopDescription {
            get {
                return ResourceManager.GetString("shopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop With Teri.
        /// </summary>
        internal static string shopTitle {
            get {
                return ResourceManager.GetString("shopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign me up for book updates!.
        /// </summary>
        internal static string signUpForBookUpdates {
            get {
                return ResourceManager.GetString("signUpForBookUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submitCommentsText {
            get {
                return ResourceManager.GetString("submitCommentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to submit comments.
        /// </summary>
        internal static string submitCommentsToolTip {
            get {
                return ResourceManager.GetString("submitCommentsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up For Our Newsletter.
        /// </summary>
        internal static string subscribeGroupText {
            get {
                return ResourceManager.GetString("subscribeGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Me Up!.
        /// </summary>
        internal static string subscribeText {
            get {
                return ResourceManager.GetString("subscribeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to sign up for our newsletter.
        /// </summary>
        internal static string subscribeToolTip {
            get {
                return ResourceManager.GetString("subscribeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subtopic:.
        /// </summary>
        internal static string subTopicsText {
            get {
                return ResourceManager.GetString("subTopicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, {0}! Thank you so much for subscribing to my newsletter!.
        /// </summary>
        internal static string thankYouNewletterSignUp {
            get {
                return ResourceManager.GetString("thankYouNewletterSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for subscribing to the TightlyCurly.org newsletter!.
        /// </summary>
        internal static string thankYouNewsletterSubject {
            get {
                return ResourceManager.GetString("thankYouNewsletterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Take Care of Our Hair: The Rules.
        /// </summary>
        internal static string theRulesDescription {
            get {
                return ResourceManager.GetString("theRulesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rules.
        /// </summary>
        internal static string theRulesTitle {
            get {
                return ResourceManager.GetString("theRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for Little Ones.
        /// </summary>
        internal static string tipsForChildrenDescription {
            get {
                return ResourceManager.GetString("tipsForChildrenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for Little Ones.
        /// </summary>
        internal static string tipsForChildrenTitle {
            get {
                return ResourceManager.GetString("tipsForChildrenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a topic:.
        /// </summary>
        internal static string topicsText {
            get {
                return ResourceManager.GetString("topicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is under construction.
        /// </summary>
        internal static string underConstructionContent {
            get {
                return ResourceManager.GetString("underConstructionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Construction.
        /// </summary>
        internal static string underConstructionDescription {
            get {
                return ResourceManager.GetString("underConstructionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Construction.
        /// </summary>
        internal static string underConstructionTitle {
            get {
                return ResourceManager.GetString("underConstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How-To Videos.
        /// </summary>
        internal static string videosDescription {
            get {
                return ResourceManager.GetString("videosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How-To Videos.
        /// </summary>
        internal static string videosTitle {
            get {
                return ResourceManager.GetString("videosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Tightly Curly Hair Site.
        /// </summary>
        internal static string welcomeDescription {
            get {
                return ResourceManager.GetString("welcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcomeTitle {
            get {
                return ResourceManager.GetString("welcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subscriptions.
        /// </summary>
        internal static string yourSubscriptions {
            get {
                return ResourceManager.GetString("yourSubscriptions", resourceCulture);
            }
        }
    }
}
