ALTER TABLE [dbo].[UsersRoles]
    ADD CONSTRAINT [PK_UsersRoles] PRIMARY KEY CLUSTERED ([UserRoleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

