//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/12/2012 5:41:01 PM
namespace TightlyCurly.Com.Web.ContentServices
{
    
    /// <summary>
    /// There are no comments for DataEntitiesDataContext in the schema.
    /// </summary>
    public partial class DataEntitiesDataContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DataEntitiesDataContext object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DataEntitiesDataContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Alligoshee.Hair.Business", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("TightlyCurly.Com.Web.ContentServices", typeName.Substring(24)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("TightlyCurly.Com.Web.ContentServices", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Alligoshee.Hair.Business.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for QuestionsQuestionCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<QuestionsQuestionCategory> QuestionsQuestionCategories
        {
            get
            {
                if ((this._QuestionsQuestionCategories == null))
                {
                    this._QuestionsQuestionCategories = base.CreateQuery<QuestionsQuestionCategory>("QuestionsQuestionCategories");
                }
                return this._QuestionsQuestionCategories;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<QuestionsQuestionCategory> _QuestionsQuestionCategories;
        /// <summary>
        /// There are no comments for QuestionCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<QuestionCategory> QuestionCategories
        {
            get
            {
                if ((this._QuestionCategories == null))
                {
                    this._QuestionCategories = base.CreateQuery<QuestionCategory>("QuestionCategories");
                }
                return this._QuestionCategories;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<QuestionCategory> _QuestionCategories;
        /// <summary>
        /// There are no comments for Questions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Question> Questions
        {
            get
            {
                if ((this._Questions == null))
                {
                    this._Questions = base.CreateQuery<Question>("Questions");
                }
                return this._Questions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Question> _Questions;
        /// <summary>
        /// There are no comments for QuestionsQuestionCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToQuestionsQuestionCategories(QuestionsQuestionCategory questionsQuestionCategory)
        {
            base.AddObject("QuestionsQuestionCategories", questionsQuestionCategory);
        }
        /// <summary>
        /// There are no comments for QuestionCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToQuestionCategories(QuestionCategory questionCategory)
        {
            base.AddObject("QuestionCategories", questionCategory);
        }
        /// <summary>
        /// There are no comments for Questions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }
    }
    /// <summary>
    /// There are no comments for Alligoshee.Hair.Business.QuestionsQuestionCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// QuestionsQuestionCategoriesId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("QuestionsQuestionCategoriesId")]
    public partial class QuestionsQuestionCategory
    {
        /// <summary>
        /// Create a new QuestionsQuestionCategory object.
        /// </summary>
        /// <param name="questionsQuestionCategoriesId">Initial value of QuestionsQuestionCategoriesId.</param>
        /// <param name="questionId">Initial value of QuestionId.</param>
        /// <param name="questionCategoryId">Initial value of QuestionCategoryId.</param>
        /// <param name="enteredDate">Initial value of EnteredDate.</param>
        /// <param name="updatedDate">Initial value of UpdatedDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static QuestionsQuestionCategory CreateQuestionsQuestionCategory(int questionsQuestionCategoriesId, int questionId, int questionCategoryId, global::System.DateTime enteredDate, global::System.DateTime updatedDate)
        {
            QuestionsQuestionCategory questionsQuestionCategory = new QuestionsQuestionCategory();
            questionsQuestionCategory.QuestionsQuestionCategoriesId = questionsQuestionCategoriesId;
            questionsQuestionCategory.QuestionId = questionId;
            questionsQuestionCategory.QuestionCategoryId = questionCategoryId;
            questionsQuestionCategory.EnteredDate = enteredDate;
            questionsQuestionCategory.UpdatedDate = updatedDate;
            return questionsQuestionCategory;
        }
        /// <summary>
        /// There are no comments for Property QuestionsQuestionCategoriesId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int QuestionsQuestionCategoriesId
        {
            get
            {
                return this._QuestionsQuestionCategoriesId;
            }
            set
            {
                this.OnQuestionsQuestionCategoriesIdChanging(value);
                this._QuestionsQuestionCategoriesId = value;
                this.OnQuestionsQuestionCategoriesIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _QuestionsQuestionCategoriesId;
        partial void OnQuestionsQuestionCategoriesIdChanging(int value);
        partial void OnQuestionsQuestionCategoriesIdChanged();
        /// <summary>
        /// There are no comments for Property QuestionId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int QuestionId
        {
            get
            {
                return this._QuestionId;
            }
            set
            {
                this.OnQuestionIdChanging(value);
                this._QuestionId = value;
                this.OnQuestionIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _QuestionId;
        partial void OnQuestionIdChanging(int value);
        partial void OnQuestionIdChanged();
        /// <summary>
        /// There are no comments for Property QuestionCategoryId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int QuestionCategoryId
        {
            get
            {
                return this._QuestionCategoryId;
            }
            set
            {
                this.OnQuestionCategoryIdChanging(value);
                this._QuestionCategoryId = value;
                this.OnQuestionCategoryIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _QuestionCategoryId;
        partial void OnQuestionCategoryIdChanging(int value);
        partial void OnQuestionCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property EnteredDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime EnteredDate
        {
            get
            {
                return this._EnteredDate;
            }
            set
            {
                this.OnEnteredDateChanging(value);
                this._EnteredDate = value;
                this.OnEnteredDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _EnteredDate;
        partial void OnEnteredDateChanging(global::System.DateTime value);
        partial void OnEnteredDateChanged();
        /// <summary>
        /// There are no comments for Property UpdatedDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return this._UpdatedDate;
            }
            set
            {
                this.OnUpdatedDateChanging(value);
                this._UpdatedDate = value;
                this.OnUpdatedDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
        /// <summary>
        /// There are no comments for QuestionCategory in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public QuestionCategory QuestionCategory
        {
            get
            {
                return this._QuestionCategory;
            }
            set
            {
                this._QuestionCategory = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private QuestionCategory _QuestionCategory;
        /// <summary>
        /// There are no comments for Question in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Question Question
        {
            get
            {
                return this._Question;
            }
            set
            {
                this._Question = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Question _Question;
    }
    /// <summary>
    /// There are no comments for Alligoshee.Hair.Business.QuestionCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// QuestionCategoryId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("QuestionCategoryId")]
    public partial class QuestionCategory
    {
        /// <summary>
        /// Create a new QuestionCategory object.
        /// </summary>
        /// <param name="questionCategoryId">Initial value of QuestionCategoryId.</param>
        /// <param name="enteredDate">Initial value of EnteredDate.</param>
        /// <param name="updatedDate">Initial value of UpdatedDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static QuestionCategory CreateQuestionCategory(int questionCategoryId, global::System.DateTime enteredDate, global::System.DateTime updatedDate)
        {
            QuestionCategory questionCategory = new QuestionCategory();
            questionCategory.QuestionCategoryId = questionCategoryId;
            questionCategory.EnteredDate = enteredDate;
            questionCategory.UpdatedDate = updatedDate;
            return questionCategory;
        }
        /// <summary>
        /// There are no comments for Property QuestionCategoryId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int QuestionCategoryId
        {
            get
            {
                return this._QuestionCategoryId;
            }
            set
            {
                this.OnQuestionCategoryIdChanging(value);
                this._QuestionCategoryId = value;
                this.OnQuestionCategoryIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _QuestionCategoryId;
        partial void OnQuestionCategoryIdChanging(int value);
        partial void OnQuestionCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for Property ParentId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ParentId
        {
            get
            {
                return this._ParentId;
            }
            set
            {
                this.OnParentIdChanging(value);
                this._ParentId = value;
                this.OnParentIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ParentId;
        partial void OnParentIdChanging(global::System.Nullable<int> value);
        partial void OnParentIdChanged();
        /// <summary>
        /// There are no comments for Property EnteredDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime EnteredDate
        {
            get
            {
                return this._EnteredDate;
            }
            set
            {
                this.OnEnteredDateChanging(value);
                this._EnteredDate = value;
                this.OnEnteredDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _EnteredDate;
        partial void OnEnteredDateChanging(global::System.DateTime value);
        partial void OnEnteredDateChanged();
        /// <summary>
        /// There are no comments for Property UpdatedDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return this._UpdatedDate;
            }
            set
            {
                this.OnUpdatedDateChanging(value);
                this._UpdatedDate = value;
                this.OnUpdatedDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
        /// <summary>
        /// There are no comments for QuestionsQuestionCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<QuestionsQuestionCategory> QuestionsQuestionCategories
        {
            get
            {
                return this._QuestionsQuestionCategories;
            }
            set
            {
                if ((value != null))
                {
                    this._QuestionsQuestionCategories = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<QuestionsQuestionCategory> _QuestionsQuestionCategories = new global::System.Collections.ObjectModel.Collection<QuestionsQuestionCategory>();
    }
    /// <summary>
    /// There are no comments for Alligoshee.Hair.Business.Question in the schema.
    /// </summary>
    /// <KeyProperties>
    /// QuestionId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("QuestionId")]
    public partial class Question
    {
        /// <summary>
        /// Create a new Question object.
        /// </summary>
        /// <param name="questionId">Initial value of QuestionId.</param>
        /// <param name="localeId">Initial value of LocaleId.</param>
        /// <param name="enteredDate">Initial value of EnteredDate.</param>
        /// <param name="updatedDate">Initial value of UpdatedDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Question CreateQuestion(int questionId, int localeId, global::System.DateTime enteredDate, global::System.DateTime updatedDate)
        {
            Question question = new Question();
            question.QuestionId = questionId;
            question.LocaleId = localeId;
            question.EnteredDate = enteredDate;
            question.UpdatedDate = updatedDate;
            return question;
        }
        /// <summary>
        /// There are no comments for Property QuestionId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int QuestionId
        {
            get
            {
                return this._QuestionId;
            }
            set
            {
                this.OnQuestionIdChanging(value);
                this._QuestionId = value;
                this.OnQuestionIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _QuestionId;
        partial void OnQuestionIdChanging(int value);
        partial void OnQuestionIdChanged();
        /// <summary>
        /// There are no comments for Property Question1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Question1
        {
            get
            {
                return this._Question1;
            }
            set
            {
                this.OnQuestion1Changing(value);
                this._Question1 = value;
                this.OnQuestion1Changed();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Question1;
        partial void OnQuestion1Changing(string value);
        partial void OnQuestion1Changed();
        /// <summary>
        /// There are no comments for Property Answer in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Answer
        {
            get
            {
                return this._Answer;
            }
            set
            {
                this.OnAnswerChanging(value);
                this._Answer = value;
                this.OnAnswerChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Answer;
        partial void OnAnswerChanging(string value);
        partial void OnAnswerChanged();
        /// <summary>
        /// There are no comments for Property LocaleId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LocaleId
        {
            get
            {
                return this._LocaleId;
            }
            set
            {
                this.OnLocaleIdChanging(value);
                this._LocaleId = value;
                this.OnLocaleIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LocaleId;
        partial void OnLocaleIdChanging(int value);
        partial void OnLocaleIdChanged();
        /// <summary>
        /// There are no comments for Property EnteredDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime EnteredDate
        {
            get
            {
                return this._EnteredDate;
            }
            set
            {
                this.OnEnteredDateChanging(value);
                this._EnteredDate = value;
                this.OnEnteredDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _EnteredDate;
        partial void OnEnteredDateChanging(global::System.DateTime value);
        partial void OnEnteredDateChanged();
        /// <summary>
        /// There are no comments for Property UpdatedDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return this._UpdatedDate;
            }
            set
            {
                this.OnUpdatedDateChanging(value);
                this._UpdatedDate = value;
                this.OnUpdatedDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
        /// <summary>
        /// There are no comments for QuestionsQuestionCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<QuestionsQuestionCategory> QuestionsQuestionCategories
        {
            get
            {
                return this._QuestionsQuestionCategories;
            }
            set
            {
                if ((value != null))
                {
                    this._QuestionsQuestionCategories = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<QuestionsQuestionCategory> _QuestionsQuestionCategories = new global::System.Collections.ObjectModel.Collection<QuestionsQuestionCategory>();
    }
}
