// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Web.UserControls {
	
	
	public partial class MessageBox {
		
		protected System.Web.UI.WebControls.Panel pnlMessageBox;
		
		protected System.Web.UI.HtmlControls.HtmlTableRow titleRow;
		
		protected System.Web.UI.WebControls.Label lblTitle;
		
		protected System.Web.UI.WebControls.HiddenField close;
		
		protected System.Web.UI.WebControls.Label lblMessage;
		
		protected AjaxControlToolkit.ModalPopupExtender messageBoxPopUp;
	}
}
