// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Web.UserControls {
	
	
	public partial class SearchControl {
		
		protected System.Web.UI.WebControls.Panel SearchPanel;
		
		protected System.Web.UI.WebControls.Label searchLabel;
		
		protected System.Web.UI.WebControls.TextBox searchText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator searchValidator;
		
		protected System.Web.UI.WebControls.Button searchButton;
		
		protected System.Web.UI.WebControls.Panel panel;
		
		protected AjaxControlToolkit.AutoCompleteExtender searchAutoComplete;
	}
}
