// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Web.MasterPages {
	
	
	public partial class Master {
		
		protected System.Web.UI.HtmlControls.HtmlHead pageHeader;
		
		protected System.Web.UI.HtmlControls.HtmlForm MasterForm;
		
		protected TightlyCurly.Com.Web.UserControls.AmazonWidget AmazonWidget;
		
		protected TightlyCurly.Com.Web.UserControls.GoogleAnalytics GoogleAnalytics;
	}
}
