// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Admin.Web.UserControls {
	
	
	public partial class ListExchangerControl {
		
		protected System.Web.UI.WebControls.Label LeftLabel;
		
		protected System.Web.UI.WebControls.Label RightLabel;
		
		protected System.Web.UI.WebControls.ListBox Left;
		
		protected System.Web.UI.WebControls.Button SwitchLeft;
		
		protected System.Web.UI.WebControls.Button SwitchRight;
		
		protected System.Web.UI.WebControls.ListBox Right;
	}
}
