// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Admin.Web {
	
	
	public partial class AnswerBankAdmin {
		
		protected System.Web.UI.WebControls.Content pageContent;
		
		protected System.Web.UI.WebControls.HiddenField SelectedIndexField;
		
		protected System.Web.UI.WebControls.ListBox QuestionsList;
		
		protected System.Web.UI.WebControls.Button EditQuestion;
		
		protected System.Web.UI.WebControls.Button DeleteQuestion;
		
		protected System.Web.UI.WebControls.HiddenField SelectedMasterCategoryField;
		
		protected System.Web.UI.WebControls.HiddenField QuestionIdField;
		
		protected System.Web.UI.WebControls.HiddenField QuestionCategoryField;
		
		protected System.Web.UI.WebControls.TextBox QuestionText;
		
		protected System.Web.UI.WebControls.TextBox AnswerText;
		
		protected System.Web.UI.WebControls.TextBox NewMasterCategory;
		
		protected System.Web.UI.WebControls.Button AddMasterCategory;
		
		protected TightlyCurly.Com.Admin.Web.UserControls.ListExchangerControl MasterCategoriesListExchanger;
		
		protected System.Web.UI.WebControls.Button DeleteMasterCategory;
		
		protected System.Web.UI.WebControls.Button ViewSubcategories;
		
		protected System.Web.UI.WebControls.TextBox NewSubcategory;
		
		protected System.Web.UI.WebControls.Button AddSubcategory;
		
		protected TightlyCurly.Com.Admin.Web.UserControls.ListExchangerControl SubCategoriesListExchanger;
		
		protected System.Web.UI.WebControls.Button DeleteSubcategory;
		
		protected System.Web.UI.WebControls.ListBox AllSubcategoriesList;
		
		protected System.Web.UI.WebControls.Button DeleteSubcategoryFromQuestion;
		
		protected System.Web.UI.WebControls.Label SelectedUriText;
		
		protected System.Web.UI.WebControls.Button SaveQuestion;
		
		protected System.Web.UI.WebControls.Button NewQuestion;
	}
}
