// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Admin.Web {
	
	
	public partial class IngredientsAdmin {
		
		protected System.Web.UI.WebControls.Content pageContent;
		
		protected System.Web.UI.WebControls.ValidationSummary ValidationSummary;
		
		protected System.Web.UI.WebControls.ListBox IngredientNames;
		
		protected System.Web.UI.WebControls.Button EditIngredient;
		
		protected System.Web.UI.WebControls.Button RemoveIngredient;
		
		protected System.Web.UI.WebControls.HiddenField Id;
		
		protected System.Web.UI.WebControls.HiddenField EnteredDate;
		
		protected System.Web.UI.WebControls.HiddenField UpdatedDate;
		
		protected System.Web.UI.WebControls.Label TitleText;
		
		protected System.Web.UI.WebControls.TextBox Title;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator TitleValidator;
		
		protected System.Web.UI.WebControls.Label AliasText;
		
		protected System.Web.UI.WebControls.TextBox Alias;
		
		protected System.Web.UI.WebControls.Label DescriptionText;
		
		protected System.Web.UI.WebControls.TextBox Description;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator DescriptionValidator;
		
		protected System.Web.UI.WebControls.Label IngredientRatingText;
		
		protected System.Web.UI.WebControls.DropDownList IngredientRating;
		
		protected TightlyCurly.Com.Admin.Web.UserControls.ListModifierControl References;
		
		protected TightlyCurly.Com.Admin.Web.UserControls.ListModifierControl Links;
		
		protected TightlyCurly.Com.Admin.Web.UserControls.ListModifierControl SeeAlso;
		
		protected System.Web.UI.WebControls.Label IngredientUri;
		
		protected System.Web.UI.WebControls.Button Save;
		
		protected System.Web.UI.WebControls.Button NewIngredient;
	}
}
