// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Admin.Web {
	
	
	public partial class PagePreview {
		
		protected System.Web.UI.WebControls.Content pageContent;
		
		protected System.Web.UI.WebControls.Literal PreviewContent;
	}
}
