// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TightlyCurly.Com.Admin.Web {
	
	
	public partial class PageAdmin {
		
		protected System.Web.UI.WebControls.Content pageContent;
		
		protected System.Web.UI.WebControls.ListBox AllPagesList;
		
		protected System.Web.UI.WebControls.Button EditPage;
		
		protected System.Web.UI.WebControls.Button DeletePage;
		
		protected System.Web.UI.WebControls.ListBox PageContentList;
		
		protected System.Web.UI.WebControls.Button EditPageContent;
		
		protected System.Web.UI.WebControls.Button DeletePageContent;
		
		protected System.Web.UI.WebControls.HiddenField IdField;
		
		protected System.Web.UI.WebControls.HiddenField PageEnteredDateField;
		
		protected System.Web.UI.WebControls.HiddenField PageUpdatedDateField;
		
		protected System.Web.UI.WebControls.Label PageNameLabel;
		
		protected System.Web.UI.WebControls.TextBox PageNameText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PageNameValidator;
		
		protected System.Web.UI.WebControls.Label ViewStatusLabel;
		
		protected System.Web.UI.WebControls.DropDownList ViewStatusList;
		
		protected System.Web.UI.WebControls.Label UriLabel;
		
		protected System.Web.UI.WebControls.TextBox UriText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator UriValidator;
		
		protected System.Web.UI.WebControls.Button NewPage;
		
		protected System.Web.UI.WebControls.Button SavePage;
		
		protected System.Web.UI.WebControls.HiddenField PageContentIdField;
		
		protected System.Web.UI.WebControls.HiddenField PageContentEnteredDateField;
		
		protected System.Web.UI.WebControls.HiddenField PageContentUpdatedDateField;
		
		protected System.Web.UI.WebControls.Label PageContentTitleLabel;
		
		protected System.Web.UI.WebControls.TextBox PageContentTitleText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PageContentTitleValidator;
		
		protected System.Web.UI.WebControls.Label PageContentMetaDescriptionLabel;
		
		protected System.Web.UI.WebControls.TextBox PageContentMetaDescriptionText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PageContentMetaDescriptionValidator;
		
		protected System.Web.UI.WebControls.Label PageContentMetaKeywordLabel;
		
		protected System.Web.UI.WebControls.TextBox PageContentMetaKeywordsText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PageContentMetaKeywordValidator;
		
		protected System.Web.UI.WebControls.Label PageContentDescriptionLabel;
		
		protected System.Web.UI.WebControls.TextBox PageContentDescriptionText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PageContentDescriptionValidator;
		
		protected System.Web.UI.WebControls.CheckBox PageContentIsActive;
		
		protected System.Web.UI.WebControls.Label PageContentLabel;
		
		protected System.Web.UI.WebControls.TextBox PageContentText;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PageContentValidator;
		
		protected System.Web.UI.WebControls.Button NewPageContent;
		
		protected System.Web.UI.WebControls.Button SavePageContent;
		
		protected System.Web.UI.WebControls.Button PreviewPageContent;
	}
}
